// originally generated by 'threeport-sdk create' for API object
// scaffolding but will not be re-generated - intended for modification

package v0

import tpapi_v0 "github.com/threeport/threeport/pkg/api/v0"

type DjangoDefinition struct {
	tpapi_v0.Common         `swaggerignore:"true" mapstructure:",squash"`
	tpapi_v0.Reconciliation `mapstructure:",squash"`
	tpapi_v0.Definition     `mapstructure:",squash"`

	// The container image for the Django application. Unlike WordPress, a
	// Django app has no canonical public image - every project builds its own -
	// so the module cannot deploy anything without it.
	Image *string `validate:"required" gorm:"not null"`

	// The Django settings module the application runs with, e.g.
	// myapp.settings.production. Passed through as DJANGO_SETTINGS_MODULE.
	SettingsModule *string `validate:"optional"`

	// The environment type used to determine config settings for a django
	// definition.
	Environment *string `validate:"optional" gorm:"default:dev"`

	// The number of pod replicas to deploy for the Django app.
	Replicas *int `validate:"optional"`

	// If true, django-admin migrate runs against the database before the
	// application is made available. Django requires this on any schema change,
	// so it defaults to true.
	RunMigrations *bool `validate:"optional" gorm:"default:true"`

	// Env holds additional literal environment variables as KEY=VALUE
	// entries, applied to every instance of this definition. Encrypted at
	// rest, since a value here may be a real credential rather than a
	// reference to one - same shape and handling as
	// MachineWorkloadDefinition.Env.
	Env *[]string `validate:"optional" gorm:"type:jsonb;serializer:json" encrypt:"true"`

	// SecretEnvVars are additional environment variables sourced from an
	// existing Kubernetes secret, applied to every instance of this
	// definition. Nothing here is plaintext, so nothing needs encryption.
	SecretEnvVars *[]DjangoSecretEnvVar `validate:"optional" gorm:"type:jsonb;serializer:json"`

	// The Kubernetes workload definition carrying the manifests this module
	// generates for the Django app and its database. The relationship tag has
	// the API create the attached object reference, so the workload definition
	// cannot be deleted while this definition still refers to it.
	KubernetesWorkloadDefinitionID *uint `validate:"optional" relationship:"owns"`

	DjangoInstances []*DjangoInstance `validate:"optional,association"`
}

type DjangoInstance struct {
	tpapi_v0.Common         `swaggerignore:"true" mapstructure:",squash"`
	tpapi_v0.Reconciliation `mapstructure:",squash"`
	tpapi_v0.Instance       `mapstructure:",squash"`

	// When using a DomainName, the subdomain to use to reach the Django
	// instance.
	SubDomain *string `validate:"optional"`

	// Env is the instance-scoped equivalent of DjangoDefinition.Env. A KEY
	// present here overrides the same KEY on the definition, for this
	// instance only. Applied when the instance is created.
	Env *[]string `validate:"optional" gorm:"type:jsonb;serializer:json" encrypt:"true"`

	// SecretEnvVars is the instance-scoped equivalent of
	// DjangoDefinition.SecretEnvVars.
	SecretEnvVars *[]DjangoSecretEnvVar `validate:"optional" gorm:"type:jsonb;serializer:json"`

	// The Kubernetes runtime to deploy this instance to. When unset the
	// module falls back to the default runtime, so a user with one cluster
	// does not have to name it.
	KubernetesRuntimeInstanceID *uint `validate:"optional" relationship:"requires"`

	// The Kubernetes workload instance deployed from this definition's
	// workload definition.
	KubernetesWorkloadInstanceID *uint `validate:"optional" relationship:"owns"`

	DjangoDefinitionID *uint `validate:"required" gorm:"not null"`
}

// DjangoSecretEnvVar is an additional environment variable sourced from an
// existing secret key rather than a literal value.
type DjangoSecretEnvVar struct {
	Name       string `json:"Name"`
	SecretName string `json:"SecretName"`
	SecretKey  string `json:"SecretKey"`
}
