// boilerplate generated by 'threeport-sdk gen' - do not edit

package v0

import (
	"encoding/json"
	"fmt"
	lib "github.com/threeport/threeport/pkg/api/lib/v0"
	api "github.com/threeport/threeport/pkg/api/v0"
	notifications "github.com/threeport/threeport/pkg/notifications/v0"
	"time"
)

const (
	ObjectTypeDjangoDefinition string = "DjangoDefinition"
	ObjectTypeDjangoInstance   string = "DjangoInstance"

	PathDjangoDefinitionVersions = "/threeport-io/django-definitions/versions"
	PathDjangoDefinitions        = "/threeport-io/v0/django-definitions"
	PathDjangoInstanceVersions   = "/threeport-io/django-instances/versions"
	PathDjangoInstances          = "/threeport-io/v0/django-instances"
)

// NotificationPayload returns the notification payload that is delivered to the
// controller when a change is made.  It includes the object as presented by the
// client when the change was made.
func (dd *DjangoDefinition) NotificationPayload(
	operation notifications.NotificationOperation,
	requeue bool,
	creationTime int64,
) (*[]byte, error) {
	notif := notifications.Notification{
		CreationTime:  &creationTime,
		Object:        dd,
		ObjectVersion: dd.GetVersion(),
		Operation:     operation,
	}

	payload, err := json.Marshal(notif)
	if err != nil {
		return &payload, fmt.Errorf("failed to marshal notification payload %+v: %w", dd, err)
	}

	return &payload, nil
}

// DecodeNotifObject takes the threeport object in the form of a
// map[string]interface and returns the typed object by marshalling into JSON
// and then unmarshalling into the typed object.  We are not using the
// mapstructure library here as that requires custom decode hooks to manage
// fields with non-native go types.
func (dd *DjangoDefinition) DecodeNotifObject(object interface{}) error {
	jsonObject, err := json.Marshal(object)
	if err != nil {
		return fmt.Errorf("failed to marshal object map from consumed notification message: %w", err)
	}
	if err := json.Unmarshal(jsonObject, &dd); err != nil {
		return fmt.Errorf("failed to unmarshal json object to typed object: %w", err)
	}
	return nil
}

// GetId returns the unique ID for the object.
func (dd *DjangoDefinition) GetId() uint {
	return *dd.ID
}

// GetType returns the object type.
func (dd *DjangoDefinition) GetType() string {
	return "DjangoDefinition"
}

// GetVersion returns the version of the API object.
func (dd *DjangoDefinition) GetVersion() string {
	return "v0"
}

// GetFullyQualifiedType returns the API-namespace-qualified type name.
func (dd *DjangoDefinition) GetFullyQualifiedType() string {
	return "threeport.io/v0.DjangoDefinition"
}

// ScheduledForDeletion returns a pointer to the DeletionScheduled timestamp
// if scheduled for deletion or nil if not scheduled for deletion.
func (dd *DjangoDefinition) ScheduledForDeletion() *time.Time {
	return dd.DeletionScheduled
}

// RelationshipTaggedForeignKeys returns the relationship-tagged foreign keys on DjangoDefinition.
func (d *DjangoDefinition) RelationshipTaggedForeignKeys() []api.RelationshipTaggedForeignKey {
	return []api.RelationshipTaggedForeignKey{{
		FieldName:    "KubernetesWorkloadDefinitionID",
		ObjectID:     d.KubernetesWorkloadDefinitionID,
		ObjectType:   new(api.KubernetesWorkloadDefinition).GetFullyQualifiedType(),
		Relationship: api.RelationshipOwns,
	}}
}

// AssociationTypes returns the fully-qualified type names of children referenced via has-many association slices on DjangoDefinition.
func (d *DjangoDefinition) AssociationTypes() []string {
	return []string{new(DjangoInstance).GetFullyQualifiedType()}
}

// EncryptedFields returns the encrypt-tagged fields on DjangoDefinition.
func (d *DjangoDefinition) EncryptedFields() []lib.EncryptedField {
	return []lib.EncryptedField{{
		Name:  "Env",
		Value: d.Env,
	}}
}

// NotificationPayload returns the notification payload that is delivered to the
// controller when a change is made.  It includes the object as presented by the
// client when the change was made.
func (di *DjangoInstance) NotificationPayload(
	operation notifications.NotificationOperation,
	requeue bool,
	creationTime int64,
) (*[]byte, error) {
	notif := notifications.Notification{
		CreationTime:  &creationTime,
		Object:        di,
		ObjectVersion: di.GetVersion(),
		Operation:     operation,
	}

	payload, err := json.Marshal(notif)
	if err != nil {
		return &payload, fmt.Errorf("failed to marshal notification payload %+v: %w", di, err)
	}

	return &payload, nil
}

// DecodeNotifObject takes the threeport object in the form of a
// map[string]interface and returns the typed object by marshalling into JSON
// and then unmarshalling into the typed object.  We are not using the
// mapstructure library here as that requires custom decode hooks to manage
// fields with non-native go types.
func (di *DjangoInstance) DecodeNotifObject(object interface{}) error {
	jsonObject, err := json.Marshal(object)
	if err != nil {
		return fmt.Errorf("failed to marshal object map from consumed notification message: %w", err)
	}
	if err := json.Unmarshal(jsonObject, &di); err != nil {
		return fmt.Errorf("failed to unmarshal json object to typed object: %w", err)
	}
	return nil
}

// GetId returns the unique ID for the object.
func (di *DjangoInstance) GetId() uint {
	return *di.ID
}

// GetType returns the object type.
func (di *DjangoInstance) GetType() string {
	return "DjangoInstance"
}

// GetVersion returns the version of the API object.
func (di *DjangoInstance) GetVersion() string {
	return "v0"
}

// GetFullyQualifiedType returns the API-namespace-qualified type name.
func (di *DjangoInstance) GetFullyQualifiedType() string {
	return "threeport.io/v0.DjangoInstance"
}

// ScheduledForDeletion returns a pointer to the DeletionScheduled timestamp
// if scheduled for deletion or nil if not scheduled for deletion.
func (di *DjangoInstance) ScheduledForDeletion() *time.Time {
	return di.DeletionScheduled
}

// RelationshipTaggedForeignKeys returns the relationship-tagged foreign keys on DjangoInstance.
func (d *DjangoInstance) RelationshipTaggedForeignKeys() []api.RelationshipTaggedForeignKey {
	return []api.RelationshipTaggedForeignKey{{
		FieldName:    "KubernetesRuntimeInstanceID",
		ObjectID:     d.KubernetesRuntimeInstanceID,
		ObjectType:   new(api.KubernetesRuntimeInstance).GetFullyQualifiedType(),
		Relationship: api.RelationshipRequires,
	}, {
		FieldName:    "KubernetesWorkloadInstanceID",
		ObjectID:     d.KubernetesWorkloadInstanceID,
		ObjectType:   new(api.KubernetesWorkloadInstance).GetFullyQualifiedType(),
		Relationship: api.RelationshipOwns,
	}}
}

// EncryptedFields returns the encrypt-tagged fields on DjangoInstance.
func (d *DjangoInstance) EncryptedFields() []lib.EncryptedField {
	return []lib.EncryptedField{{
		Name:  "Env",
		Value: d.Env,
	}}
}
