// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package cmd

import (
	config_v0 "django-threeport-module/pkg/config/v0"
	"errors"
	"fmt"
	cobra "github.com/spf13/cobra"
	tptctl_cmd "github.com/threeport/threeport/cmd/tptctl/cmd"
	cli "github.com/threeport/threeport/pkg/cli/v0"
	"os"
	yaml "sigs.k8s.io/yaml"
)

var (
	djangoName       string
	djangoConfigPath string
	djangoStdin      bool
	djangoVersion    string
	djangoOutput     string
	djangoDecrypt    bool
)

// getEncryptionKey returns the control plane's encryption key when the user
// asked for secrets to be decrypted, and an empty string otherwise, which makes
// the config layer redact encrypted values instead.
func getEncryptionKey(requestedControlPlane string) string {
	if !djangoDecrypt {
		return ""
	}
	threeportConfig, _, err := cli.GetThreeportConfig(cliArgs.ControlPlaneName)
	if err != nil {
		cli.Error("failed to get threeport config", err)
		os.Exit(1)
	}
	key, err := threeportConfig.GetThreeportEncryptionKey(requestedControlPlane)
	if err != nil {
		cli.Error("failed to get encryption key from threeport config", err)
		os.Exit(1)
	}
	return key
}

///////////////////////////////////////////////////////////////////////////////
// Django
///////////////////////////////////////////////////////////////////////////////

// GetDjangosCmd represents the command 'tptctl django get djangos'
var GetDjangosCmd = &cobra.Command{
	Aliases: []string{"django"},
	Example: "  # get all djangos\n  tptctl django get djangos\n\n  # get a specific django\n  tptctl django get django --name some-django",
	Long:    "Get djangos from the system. Use --name to get a specific django. A django is a unified abstraction of a django definition and django instance.",
	PreRun:  CommandPreRunFunc,
	Run: func(cmd *cobra.Command, args []string) {
		apiClient, _, apiEndpoint, requestedControlPlane := tptctl_cmd.GetClientContext(cmd)

		// flag validation
		if err := cli.ValidateConfigNameFlags(
			djangoConfigPath,
			djangoName,
			"django",
		); err != nil {
			cli.Error("flag validation failed", err)
			os.Exit(1)
		}

		// get django based on version
		switch djangoVersion {
		case "v0":
			// load django values
			djangoConfig := config_v0.DjangoConfig{}
			if djangoConfigPath != "" || djangoStdin {
				configContent, err := cli.ReadConfigContent(djangoConfigPath, djangoStdin)
				if err != nil {
					cli.Error("failed to read config", err)
					os.Exit(1)
				}
				if err := yaml.UnmarshalStrict(configContent, &djangoConfig); err != nil {
					cli.Error("failed to unmarshal config file yaml content", err)
					os.Exit(1)
				}
			} else if djangoName != "" {
				djangoConfig = config_v0.DjangoConfig{
					Django: config_v0.DjangoValues{
						Name: &djangoName,
					},
				}
			}

			// get django
			djangoConfigs, err := djangoConfig.Get(apiClient, apiEndpoint, getEncryptionKey(requestedControlPlane))
			if err != nil {
				cli.Error("failed to retrieve django", err)
				os.Exit(1)
			}

			// check if django exists
			if len(*djangoConfigs) == 0 {
				cli.Info(fmt.Sprintf(
					"no djangos found that are currently managed by %s threeport control plane",
					requestedControlPlane,
				))
				os.Exit(0)
			}

			// write the output
			switch djangoOutput {
			case "tabular":
				if err := outputGetv0DjangosCmd(djangoConfigs); err != nil {
					cli.Error("failed to produce output", err)
					os.Exit(1)
				}
			case "yaml":
				if err := cli.YamlObjectOutput(*djangoConfigs); err != nil {
					cli.Error("failed to produce YAML output", err)
					os.Exit(1)
				}
			case "json":
				if err := cli.JsonObjectOutput(*djangoConfigs); err != nil {
					cli.Error("failed to produce JSON output", err)
					os.Exit(1)
				}
			default:
				cli.Error("", fmt.Errorf("unrecognized output format: %s", djangoOutput))
				os.Exit(1)
			}
		default:
			cli.Error("", errors.New("unrecognized object version"))
			os.Exit(1)
		}
	},
	Short:        "Get djangos from the system",
	SilenceUsage: true,
	Use:          "djangos",
}

func init() {
	GetCmd.AddCommand(GetDjangosCmd)

	GetDjangosCmd.Flags().StringVarP(
		&djangoName,
		"name", "n", "", "Name of django.",
	)
	GetDjangosCmd.Flags().StringVarP(
		&djangoConfigPath,
		"config", "c", "", "Path to file with django config.",
	)
	GetDjangosCmd.Flags().StringVarP(
		&djangoVersion,
		"version", "v", "v0", "Version of django objects to retrieve. One of: [v0]",
	)
	GetDjangosCmd.Flags().StringVarP(
		&djangoOutput,
		"output", "o", "tabular", "Output format for django objects. One of: [tabular, yaml, json]",
	)
	GetDjangosCmd.Flags().StringVarP(
		&cliArgs.ControlPlaneName,
		"control-plane-name", "i", "", "Optional. Name of control plane. Will default to current control plane if not provided.",
	)
	GetDjangosCmd.Flags().BoolVarP(
		&djangoDecrypt,
		"decrypt-secrets", "d", false, "Decrypt any encrypted secrets in output.",
	)
}

// CreateDjangoCmd represents the command 'tptctl django create django'
var CreateDjangoCmd = &cobra.Command{
	Example: "  # create a new django using a config file\n  tptctl django create django --config path/to/config.yaml",
	Long:    "Create a new django. A django is a unified abstraction of a django definition and django instance. This command creates both a new django definition and django instance.",
	PreRun:  CommandPreRunFunc,
	Run: func(cmd *cobra.Command, args []string) {
		apiClient, _, apiEndpoint, _ := tptctl_cmd.GetClientContext(cmd)

		// read django config
		configContent, err := cli.ReadConfigContent(djangoConfigPath, djangoStdin)
		if err != nil {
			cli.Error("failed to read config", err)
			os.Exit(1)
		}

		// create django based on version
		switch djangoVersion {
		case "v0":
			var djangoConfig config_v0.DjangoConfig
			if err := yaml.UnmarshalStrict(configContent, &djangoConfig); err != nil {
				cli.Error("failed to unmarshal config file yaml content", err)
				os.Exit(1)
			}

			// create django
			createdDjangoSlice, err := djangoConfig.Create(
				apiClient,
				apiEndpoint,
			)
			if err != nil {
				cli.Error("failed to create django", err)
				os.Exit(1)
			}

			// check the result of the create
			if createdDjangoSlice == nil || len(*createdDjangoSlice) == 0 {
				cli.Error("failed to create django", errors.New("no djangos received after create"))
				os.Exit(1)
			}
			createdDjango := (*createdDjangoSlice)[0]

			cli.Info(fmt.Sprintf("django definition and instance with name %s created", *createdDjango.Django.Name))
			cli.Complete(fmt.Sprintf("django %s created", *createdDjango.Django.Name))
		default:
			cli.Error("", errors.New("unrecognized object version"))
			os.Exit(1)
		}
	},
	Short:        "Create a new django",
	SilenceUsage: true,
	Use:          "django",
}

func init() {
	CreateCmd.AddCommand(CreateDjangoCmd)

	CreateDjangoCmd.Flags().StringVarP(
		&djangoConfigPath,
		"config", "c", "", "Path to file with django config.",
	)
	CreateDjangoCmd.Flags().BoolVar(
		&djangoStdin,
		"stdin", false, "Read config from stdin instead of file.",
	)
	CreateDjangoCmd.Flags().StringVarP(
		&cliArgs.ControlPlaneName,
		"control-plane-name", "i", "", "Optional. Name of control plane. Will default to current control plane if not provided.",
	)
	CreateDjangoCmd.Flags().StringVarP(
		&djangoVersion,
		"version", "v", "v0", "Version of djangos object to create. One of: [v0]",
	)
}

// DeleteDjangoCmd represents the command 'tptctl django delete django'
var DeleteDjangoCmd = &cobra.Command{
	Example: "  # delete using a config file\n  tptctl django delete django --config path/to/config.yaml\n\n  # delete using name\n  tptctl django delete django --name some-django",
	Long:    "Delete an existing django. This command deletes an existing django definition and django instance.",
	PreRun:  CommandPreRunFunc,
	Run: func(cmd *cobra.Command, args []string) {
		apiClient, _, apiEndpoint, _ := tptctl_cmd.GetClientContext(cmd)

		// flag validation
		if djangoConfigPath == "" {
			cli.Error("flag validation failed", errors.New("config file path is required"))
		}

		// read django config
		configContent, err := cli.ReadConfigContent(djangoConfigPath, djangoStdin)
		if err != nil {
			cli.Error("failed to read config", err)
			os.Exit(1)
		}

		// delete django based on version
		switch djangoVersion {
		case "v0":
			var djangoConfig config_v0.DjangoConfig
			if err := yaml.UnmarshalStrict(configContent, &djangoConfig); err != nil {
				cli.Error("failed to unmarshal config file yaml content", err)
				os.Exit(1)
			}

			// delete django
			_, err = djangoConfig.Delete(apiClient, apiEndpoint)
			if err != nil {
				cli.Error("failed to delete django", err)
				os.Exit(1)
			}

			cli.Info(fmt.Sprintf("django definition %s deleted", *djangoConfig.Django.Name))
			cli.Info(fmt.Sprintf("django instance %s deleted", *djangoConfig.Django.Name))
			cli.Complete(fmt.Sprintf("django %s deleted", *djangoConfig.Django.Name))
		default:
			cli.Error("", errors.New("unrecognized object version"))
			os.Exit(1)
		}
	},
	Short:        "Delete an existing django",
	SilenceUsage: true,
	Use:          "django",
}

func init() {
	DeleteCmd.AddCommand(DeleteDjangoCmd)

	DeleteDjangoCmd.Flags().StringVarP(
		&djangoConfigPath,
		"config", "c", "", "Path to file with django config.",
	)
	DeleteDjangoCmd.Flags().StringVarP(
		&cliArgs.ControlPlaneName,
		"control-plane-name", "i", "", "Optional. Name of control plane. Will default to current control plane if not provided.",
	)
	DeleteDjangoCmd.Flags().StringVarP(
		&djangoVersion,
		"version", "v", "v0", "Version of djangos object to delete. One of: [v0]",
	)
}

///////////////////////////////////////////////////////////////////////////////
// DjangoDefinition
///////////////////////////////////////////////////////////////////////////////

// GetDjangoDefinitionsCmd represents the command 'tptctl django get django-definitions'
var GetDjangoDefinitionsCmd = &cobra.Command{
	Aliases: []string{"django-definition"},
	Example: "  # get all django definitions\n  tptctl django get django-definitions\n\n  # get a specific django definition\n  tptctl django get django-definition --name some-django-definition",
	Long:    "Get django definitions from the system. Use --name to get a specific django definition.",
	PreRun:  CommandPreRunFunc,
	Run: func(cmd *cobra.Command, args []string) {
		apiClient, _, apiEndpoint, requestedControlPlane := tptctl_cmd.GetClientContext(cmd)

		// flag validation
		if err := cli.ValidateConfigNameFlags(
			djangoConfigPath,
			djangoName,
			"django definition",
		); err != nil {
			cli.Error("flag validation failed", err)
			os.Exit(1)
		}

		switch djangoVersion {
		case "v0":
			// load values
			djangoDefinitionConfig := config_v0.DjangoDefinitionConfig{}
			if djangoConfigPath != "" || djangoStdin {
				configContent, err := cli.ReadConfigContent(djangoConfigPath, djangoStdin)
				if err != nil {
					cli.Error("failed to read config", err)
					os.Exit(1)
				}
				if err := yaml.UnmarshalStrict(configContent, &djangoDefinitionConfig); err != nil {
					cli.Error("failed to unmarshal config file yaml content", err)
					os.Exit(1)
				}
			} else if djangoName != "" {
				djangoDefinitionConfig = config_v0.DjangoDefinitionConfig{
					DjangoDefinition: config_v0.DjangoDefinitionValues{
						Name: &djangoName,
					},
				}
			}

			// get django definitions
			djangoDefinitions, err := djangoDefinitionConfig.Get(apiClient, apiEndpoint, getEncryptionKey(requestedControlPlane))
			if err != nil {
				cli.Error("failed to retrieve django definitions", err)
				os.Exit(1)
			}

			// check if django definition exists
			if len(*djangoDefinitions) == 0 {
				cli.Info(fmt.Sprintf(
					"no django definitions found that are currently managed by %s threeport control plane",
					requestedControlPlane,
				))
				os.Exit(0)
			}

			// write the output
			switch djangoOutput {
			case "tabular":
				if err := outputGetv0DjangoDefinitionsCmd(djangoDefinitions); err != nil {
					cli.Error("failed to produce output", err)
					os.Exit(1)
				}
			case "yaml":
				if err := cli.YamlObjectOutput(*djangoDefinitions); err != nil {
					cli.Error("failed to produce YAML output", err)
					os.Exit(1)
				}
			case "json":
				if err := cli.JsonObjectOutput(*djangoDefinitions); err != nil {
					cli.Error("failed to produce JSON output", err)
					os.Exit(1)
				}
			default:
				cli.Error("", fmt.Errorf("unrecognized output format: %s", djangoOutput))
				os.Exit(1)
			}
		default:
			cli.Error("", errors.New("unrecognized object version"))
			os.Exit(1)
		}
	},
	Short:        "Get django definitions from the system",
	SilenceUsage: true,
	Use:          "django-definitions",
}

func init() {
	GetCmd.AddCommand(GetDjangoDefinitionsCmd)

	GetDjangoDefinitionsCmd.Flags().StringVarP(
		&djangoName,
		"name", "n", "", "Name of django definition.",
	)
	GetDjangoDefinitionsCmd.Flags().StringVarP(
		&djangoConfigPath,
		"config", "c", "", "Path to file with django definition config.",
	)
	GetDjangoDefinitionsCmd.Flags().StringVarP(
		&djangoVersion,
		"version", "v", "v0", "Version of django definition objects to retrieve. One of: [v0]",
	)
	GetDjangoDefinitionsCmd.Flags().StringVarP(
		&djangoOutput,
		"output", "o", "tabular", "Output format for django definition objects. One of: [tabular, yaml, json]",
	)
	GetDjangoDefinitionsCmd.Flags().StringVarP(
		&cliArgs.ControlPlaneName,
		"control-plane-name", "i", "", "Optional. Name of control plane. Will default to current control plane if not provided.",
	)
	GetDjangoDefinitionsCmd.Flags().BoolVarP(
		&djangoDecrypt,
		"decrypt-secrets", "d", false, "Decrypt any encrypted secrets in output.",
	)
}

// CreateDjangoDefinitionCmd represents the command 'tptctl django create django-definition'
var CreateDjangoDefinitionCmd = &cobra.Command{
	Example: "  # create a new django definition using a config file\n  tptctl django create django-definition --config path/to/config.yaml",
	Long:    "Create a new django definition.",
	PreRun:  CommandPreRunFunc,
	Run: func(cmd *cobra.Command, args []string) {
		apiClient, _, apiEndpoint, _ := tptctl_cmd.GetClientContext(cmd)

		// read django definition config
		configContent, err := cli.ReadConfigContent(djangoConfigPath, djangoStdin)
		if err != nil {
			cli.Error("failed to read config", err)
			os.Exit(1)
		}
		// create django definition based on version
		switch djangoVersion {
		case "v0":
			var djangoDefinitionConfig config_v0.DjangoDefinitionConfig
			if err := yaml.UnmarshalStrict(configContent, &djangoDefinitionConfig); err != nil {
				cli.Error("failed to unmarshal config file yaml content", err)
				os.Exit(1)
			}

			// create django definition
			createdDjangoDefinition, err := djangoDefinitionConfig.Create(apiClient, apiEndpoint)
			if err != nil {
				cli.Error("failed to create django definition", err)
				os.Exit(1)
			}

			cli.Complete(fmt.Sprintf("django definition %s created", *createdDjangoDefinition.DjangoDefinition.Name))
		default:
			cli.Error("", errors.New("unrecognized object version"))
			os.Exit(1)
		}
	},
	Short:        "Create a new django definition",
	SilenceUsage: true,
	Use:          "django-definition",
}

func init() {
	CreateCmd.AddCommand(CreateDjangoDefinitionCmd)

	CreateDjangoDefinitionCmd.Flags().StringVarP(
		&djangoConfigPath,
		"config", "c", "", "Path to file with django definition config.",
	)
	CreateDjangoDefinitionCmd.Flags().BoolVar(
		&djangoStdin,
		"stdin", false, "Read config from stdin instead of file.",
	)
	CreateDjangoDefinitionCmd.Flags().StringVarP(
		&cliArgs.ControlPlaneName,
		"control-plane-name", "i", "", "Optional. Name of control plane. Will default to current control plane if not provided.",
	)
	CreateDjangoDefinitionCmd.Flags().StringVarP(
		&djangoVersion,
		"version", "v", "v0", "Version of django definitions object to create. One of: [v0]",
	)
}

// ReplaceDjangoDefinitionCmd represents the command 'tptctl django replace django-definition'
var ReplaceDjangoDefinitionCmd = &cobra.Command{
	Example: "  # replace using a config file\n  tptctl django replace django-definition --config path/to/config.yaml --name some-django-definition",
	Long:    "Replace an existing django definition.\n Note that the entire object will replaced with a PUT request.\n All fields must be provided in the config file.",
	PreRun:  CommandPreRunFunc,
	Run: func(cmd *cobra.Command, args []string) {
		apiClient, _, apiEndpoint, _ := tptctl_cmd.GetClientContext(cmd)

		// replace django definition based on version
		switch djangoVersion {
		case "v0":
			var djangoDefinitionConfig config_v0.DjangoDefinitionConfig
			// load django definition config
			configContent, err := cli.ReadConfigContent(djangoConfigPath, djangoStdin)
			if err != nil {
				cli.Error("failed to read config", err)
				os.Exit(1)
			}
			if err := yaml.UnmarshalStrict(configContent, &djangoDefinitionConfig); err != nil {
				cli.Error("failed to unmarshal config file yaml content", err)
				os.Exit(1)
			}

			// replace django definition
			updatedDjangoDefinition, err := djangoDefinitionConfig.Replace(apiClient, apiEndpoint, djangoName)
			if err != nil {
				cli.Error("failed to update django definition", err)
				os.Exit(1)
			}

			cli.Complete(fmt.Sprintf("django definition %s updated", *updatedDjangoDefinition.DjangoDefinition.Name))
		default:
			cli.Error("", errors.New("unrecognized object version"))
			os.Exit(1)
		}
	},
	Short:        "Replace an existing django definition",
	SilenceUsage: true,
	Use:          "django-definition",
}

func init() {
	ReplaceCmd.AddCommand(ReplaceDjangoDefinitionCmd)

	ReplaceDjangoDefinitionCmd.Flags().StringVarP(
		&djangoConfigPath,
		"config", "c", "", "Path to file with django definition config.  The config file must be a complete config, i.e. the provided config will be used to replace the entire existing config for the object with a PUT request.",
	)
	ReplaceDjangoDefinitionCmd.Flags().BoolVar(
		&djangoStdin,
		"stdin", false, "Read config from stdin instead of file.",
	)
	ReplaceDjangoDefinitionCmd.Flags().StringVarP(
		&djangoName,
		"name", "n", "", "Name of existing django definition to replace.  If the name in the django definition config is different from the name provided here, the name of the existing object will be updated with the name in the config.",
	)
	ReplaceDjangoDefinitionCmd.MarkFlagRequired("name")
	ReplaceDjangoDefinitionCmd.Flags().StringVarP(
		&cliArgs.ControlPlaneName,
		"control-plane-name", "i", "", "Optional. Name of control plane. Will default to current control plane if not provided.",
	)
	ReplaceDjangoDefinitionCmd.Flags().StringVarP(
		&djangoVersion,
		"version", "v", "v0", "Version of django definitions object to replace. One of: [v0]",
	)
}

// DeleteDjangoDefinitionCmd represents the command 'tptctl django delete django-definition'
var DeleteDjangoDefinitionCmd = &cobra.Command{
	Example: "  # delete using a config file\n  tptctl django delete django-definition --config path/to/config.yaml\n\n  # delete using name\n  tptctl django delete django-definition --name some-django-definition",
	Long:    "Delete an existing django definition.",
	PreRun:  CommandPreRunFunc,
	Run: func(cmd *cobra.Command, args []string) {
		apiClient, _, apiEndpoint, _ := tptctl_cmd.GetClientContext(cmd)

		// flag validation
		if err := cli.ValidateConfigNameFlags(
			djangoConfigPath,
			djangoName,
			"django definition",
		); err != nil {
			cli.Error("flag validation failed", err)
			os.Exit(1)
		}

		// delete django definition based on version
		switch djangoVersion {
		case "v0":
			var djangoDefinitionConfig config_v0.DjangoDefinitionConfig
			if djangoConfigPath != "" || djangoStdin {
				// load django definition config
				configContent, err := cli.ReadConfigContent(djangoConfigPath, djangoStdin)
				if err != nil {
					cli.Error("failed to read config", err)
					os.Exit(1)
				}
				if err := yaml.UnmarshalStrict(configContent, &djangoDefinitionConfig); err != nil {
					cli.Error("failed to unmarshal config file yaml content", err)
					os.Exit(1)
				}
			} else {
				djangoDefinitionConfig = config_v0.DjangoDefinitionConfig{
					DjangoDefinition: config_v0.DjangoDefinitionValues{
						Name: &djangoName,
					},
				}
			}

			// delete django definition
			deletedDjangoDefinition, err := djangoDefinitionConfig.Delete(apiClient, apiEndpoint)
			if err != nil {
				cli.Error("failed to delete django definition", err)
				os.Exit(1)
			}

			cli.Complete(fmt.Sprintf("django definition %s deleted", *deletedDjangoDefinition.DjangoDefinition.Name))
		default:
			cli.Error("", errors.New("unrecognized object version"))
			os.Exit(1)
		}
	},
	Short:        "Delete an existing django definition",
	SilenceUsage: true,
	Use:          "django-definition",
}

func init() {
	DeleteCmd.AddCommand(DeleteDjangoDefinitionCmd)

	DeleteDjangoDefinitionCmd.Flags().StringVarP(
		&djangoConfigPath,
		"config", "c", "", "Path to file with django definition config.",
	)
	DeleteDjangoDefinitionCmd.Flags().StringVarP(
		&djangoName,
		"name", "n", "", "Name of django definition.",
	)
	DeleteDjangoDefinitionCmd.Flags().StringVarP(
		&cliArgs.ControlPlaneName,
		"control-plane-name", "i", "", "Optional. Name of control plane. Will default to current control plane if not provided.",
	)
	DeleteDjangoDefinitionCmd.Flags().StringVarP(
		&djangoVersion,
		"version", "v", "v0", "Version of django definitions object to delete. One of: [v0]",
	)
}

///////////////////////////////////////////////////////////////////////////////
// DjangoInstance
///////////////////////////////////////////////////////////////////////////////

// GetDjangoInstancesCmd represents the command 'tptctl django get django-instances'
var GetDjangoInstancesCmd = &cobra.Command{
	Aliases: []string{"django-instance"},
	Example: "  # get all django instances\n  tptctl django get django-instances\n\n  # get a specific django instance\n  tptctl django get django-instance --name some-django-instance",
	Long:    "Get django instances from the system. Use --name to get a specific django instance.",
	PreRun:  CommandPreRunFunc,
	Run: func(cmd *cobra.Command, args []string) {
		apiClient, _, apiEndpoint, requestedControlPlane := tptctl_cmd.GetClientContext(cmd)

		// flag validation
		if err := cli.ValidateConfigNameFlags(
			djangoConfigPath,
			djangoName,
			"django instance",
		); err != nil {
			cli.Error("flag validation failed", err)
			os.Exit(1)
		}

		switch djangoVersion {
		case "v0":
			// load values
			djangoInstanceConfig := config_v0.DjangoInstanceConfig{}
			if djangoConfigPath != "" || djangoStdin {
				configContent, err := cli.ReadConfigContent(djangoConfigPath, djangoStdin)
				if err != nil {
					cli.Error("failed to read config", err)
					os.Exit(1)
				}
				if err := yaml.UnmarshalStrict(configContent, &djangoInstanceConfig); err != nil {
					cli.Error("failed to unmarshal config file yaml content", err)
					os.Exit(1)
				}
			} else if djangoName != "" {
				djangoInstanceConfig = config_v0.DjangoInstanceConfig{
					DjangoInstance: config_v0.DjangoInstanceValues{
						Name: &djangoName,
					},
				}
			}

			// get django instances
			djangoInstances, err := djangoInstanceConfig.Get(apiClient, apiEndpoint, getEncryptionKey(requestedControlPlane))
			if err != nil {
				cli.Error("failed to retrieve django instances", err)
				os.Exit(1)
			}

			// check if django instance exists
			if len(*djangoInstances) == 0 {
				cli.Info(fmt.Sprintf(
					"no django instances found that are currently managed by %s threeport control plane",
					requestedControlPlane,
				))
				os.Exit(0)
			}

			// write the output
			switch djangoOutput {
			case "tabular":
				if err := outputGetv0DjangoInstancesCmd(djangoInstances); err != nil {
					cli.Error("failed to produce output", err)
					os.Exit(1)
				}
			case "yaml":
				if err := cli.YamlObjectOutput(*djangoInstances); err != nil {
					cli.Error("failed to produce YAML output", err)
					os.Exit(1)
				}
			case "json":
				if err := cli.JsonObjectOutput(*djangoInstances); err != nil {
					cli.Error("failed to produce JSON output", err)
					os.Exit(1)
				}
			default:
				cli.Error("", fmt.Errorf("unrecognized output format: %s", djangoOutput))
				os.Exit(1)
			}
		default:
			cli.Error("", errors.New("unrecognized object version"))
			os.Exit(1)
		}
	},
	Short:        "Get django instances from the system",
	SilenceUsage: true,
	Use:          "django-instances",
}

func init() {
	GetCmd.AddCommand(GetDjangoInstancesCmd)

	GetDjangoInstancesCmd.Flags().StringVarP(
		&djangoName,
		"name", "n", "", "Name of django instance.",
	)
	GetDjangoInstancesCmd.Flags().StringVarP(
		&djangoConfigPath,
		"config", "c", "", "Path to file with django instance config.",
	)
	GetDjangoInstancesCmd.Flags().StringVarP(
		&djangoVersion,
		"version", "v", "v0", "Version of django instance objects to retrieve. One of: [v0]",
	)
	GetDjangoInstancesCmd.Flags().StringVarP(
		&djangoOutput,
		"output", "o", "tabular", "Output format for django instance objects. One of: [tabular, yaml, json]",
	)
	GetDjangoInstancesCmd.Flags().StringVarP(
		&cliArgs.ControlPlaneName,
		"control-plane-name", "i", "", "Optional. Name of control plane. Will default to current control plane if not provided.",
	)
	GetDjangoInstancesCmd.Flags().BoolVarP(
		&djangoDecrypt,
		"decrypt-secrets", "d", false, "Decrypt any encrypted secrets in output.",
	)
}

// CreateDjangoInstanceCmd represents the command 'tptctl django create django-instance'
var CreateDjangoInstanceCmd = &cobra.Command{
	Example: "  # create a new django instance using a config file\n  tptctl django create django-instance --config path/to/config.yaml",
	Long:    "Create a new django instance.",
	PreRun:  CommandPreRunFunc,
	Run: func(cmd *cobra.Command, args []string) {
		apiClient, _, apiEndpoint, _ := tptctl_cmd.GetClientContext(cmd)

		// read django instance config
		configContent, err := cli.ReadConfigContent(djangoConfigPath, djangoStdin)
		if err != nil {
			cli.Error("failed to read config", err)
			os.Exit(1)
		}
		// create django instance based on version
		switch djangoVersion {
		case "v0":
			var djangoInstanceConfig config_v0.DjangoInstanceConfig
			if err := yaml.UnmarshalStrict(configContent, &djangoInstanceConfig); err != nil {
				cli.Error("failed to unmarshal config file yaml content", err)
				os.Exit(1)
			}

			// create django instance
			createdDjangoInstance, err := djangoInstanceConfig.Create(apiClient, apiEndpoint)
			if err != nil {
				cli.Error("failed to create django instance", err)
				os.Exit(1)
			}

			cli.Complete(fmt.Sprintf("django instance %s created", *createdDjangoInstance.DjangoInstance.Name))
		default:
			cli.Error("", errors.New("unrecognized object version"))
			os.Exit(1)
		}
	},
	Short:        "Create a new django instance",
	SilenceUsage: true,
	Use:          "django-instance",
}

func init() {
	CreateCmd.AddCommand(CreateDjangoInstanceCmd)

	CreateDjangoInstanceCmd.Flags().StringVarP(
		&djangoConfigPath,
		"config", "c", "", "Path to file with django instance config.",
	)
	CreateDjangoInstanceCmd.Flags().BoolVar(
		&djangoStdin,
		"stdin", false, "Read config from stdin instead of file.",
	)
	CreateDjangoInstanceCmd.Flags().StringVarP(
		&cliArgs.ControlPlaneName,
		"control-plane-name", "i", "", "Optional. Name of control plane. Will default to current control plane if not provided.",
	)
	CreateDjangoInstanceCmd.Flags().StringVarP(
		&djangoVersion,
		"version", "v", "v0", "Version of django instances object to create. One of: [v0]",
	)
}

// ReplaceDjangoInstanceCmd represents the command 'tptctl django replace django-instance'
var ReplaceDjangoInstanceCmd = &cobra.Command{
	Example: "  # replace using a config file\n  tptctl django replace django-instance --config path/to/config.yaml --name some-django-instance",
	Long:    "Replace an existing django instance.\n Note that the entire object will replaced with a PUT request.\n All fields must be provided in the config file.",
	PreRun:  CommandPreRunFunc,
	Run: func(cmd *cobra.Command, args []string) {
		apiClient, _, apiEndpoint, _ := tptctl_cmd.GetClientContext(cmd)

		// replace django instance based on version
		switch djangoVersion {
		case "v0":
			var djangoInstanceConfig config_v0.DjangoInstanceConfig
			// load django instance config
			configContent, err := cli.ReadConfigContent(djangoConfigPath, djangoStdin)
			if err != nil {
				cli.Error("failed to read config", err)
				os.Exit(1)
			}
			if err := yaml.UnmarshalStrict(configContent, &djangoInstanceConfig); err != nil {
				cli.Error("failed to unmarshal config file yaml content", err)
				os.Exit(1)
			}

			// replace django instance
			updatedDjangoInstance, err := djangoInstanceConfig.Replace(apiClient, apiEndpoint, djangoName)
			if err != nil {
				cli.Error("failed to update django instance", err)
				os.Exit(1)
			}

			cli.Complete(fmt.Sprintf("django instance %s updated", *updatedDjangoInstance.DjangoInstance.Name))
		default:
			cli.Error("", errors.New("unrecognized object version"))
			os.Exit(1)
		}
	},
	Short:        "Replace an existing django instance",
	SilenceUsage: true,
	Use:          "django-instance",
}

func init() {
	ReplaceCmd.AddCommand(ReplaceDjangoInstanceCmd)

	ReplaceDjangoInstanceCmd.Flags().StringVarP(
		&djangoConfigPath,
		"config", "c", "", "Path to file with django instance config.  The config file must be a complete config, i.e. the provided config will be used to replace the entire existing config for the object with a PUT request.",
	)
	ReplaceDjangoInstanceCmd.Flags().BoolVar(
		&djangoStdin,
		"stdin", false, "Read config from stdin instead of file.",
	)
	ReplaceDjangoInstanceCmd.Flags().StringVarP(
		&djangoName,
		"name", "n", "", "Name of existing django instance to replace.  If the name in the django instance config is different from the name provided here, the name of the existing object will be updated with the name in the config.",
	)
	ReplaceDjangoInstanceCmd.MarkFlagRequired("name")
	ReplaceDjangoInstanceCmd.Flags().StringVarP(
		&cliArgs.ControlPlaneName,
		"control-plane-name", "i", "", "Optional. Name of control plane. Will default to current control plane if not provided.",
	)
	ReplaceDjangoInstanceCmd.Flags().StringVarP(
		&djangoVersion,
		"version", "v", "v0", "Version of django instances object to replace. One of: [v0]",
	)
}

// DeleteDjangoInstanceCmd represents the command 'tptctl django delete django-instance'
var DeleteDjangoInstanceCmd = &cobra.Command{
	Example: "  # delete using a config file\n  tptctl django delete django-instance --config path/to/config.yaml\n\n  # delete using name\n  tptctl django delete django-instance --name some-django-instance",
	Long:    "Delete an existing django instance.",
	PreRun:  CommandPreRunFunc,
	Run: func(cmd *cobra.Command, args []string) {
		apiClient, _, apiEndpoint, _ := tptctl_cmd.GetClientContext(cmd)

		// flag validation
		if err := cli.ValidateConfigNameFlags(
			djangoConfigPath,
			djangoName,
			"django instance",
		); err != nil {
			cli.Error("flag validation failed", err)
			os.Exit(1)
		}

		// delete django instance based on version
		switch djangoVersion {
		case "v0":
			var djangoInstanceConfig config_v0.DjangoInstanceConfig
			if djangoConfigPath != "" || djangoStdin {
				// load django instance config
				configContent, err := cli.ReadConfigContent(djangoConfigPath, djangoStdin)
				if err != nil {
					cli.Error("failed to read config", err)
					os.Exit(1)
				}
				if err := yaml.UnmarshalStrict(configContent, &djangoInstanceConfig); err != nil {
					cli.Error("failed to unmarshal config file yaml content", err)
					os.Exit(1)
				}
			} else {
				djangoInstanceConfig = config_v0.DjangoInstanceConfig{
					DjangoInstance: config_v0.DjangoInstanceValues{
						Name: &djangoName,
					},
				}
			}

			// delete django instance
			deletedDjangoInstance, err := djangoInstanceConfig.Delete(apiClient, apiEndpoint)
			if err != nil {
				cli.Error("failed to delete django instance", err)
				os.Exit(1)
			}

			cli.Complete(fmt.Sprintf("django instance %s deleted", *deletedDjangoInstance.DjangoInstance.Name))
		default:
			cli.Error("", errors.New("unrecognized object version"))
			os.Exit(1)
		}
	},
	Short:        "Delete an existing django instance",
	SilenceUsage: true,
	Use:          "django-instance",
}

func init() {
	DeleteCmd.AddCommand(DeleteDjangoInstanceCmd)

	DeleteDjangoInstanceCmd.Flags().StringVarP(
		&djangoConfigPath,
		"config", "c", "", "Path to file with django instance config.",
	)
	DeleteDjangoInstanceCmd.Flags().StringVarP(
		&djangoName,
		"name", "n", "", "Name of django instance.",
	)
	DeleteDjangoInstanceCmd.Flags().StringVarP(
		&cliArgs.ControlPlaneName,
		"control-plane-name", "i", "", "Optional. Name of control plane. Will default to current control plane if not provided.",
	)
	DeleteDjangoInstanceCmd.Flags().StringVarP(
		&djangoVersion,
		"version", "v", "v0", "Version of django instances object to delete. One of: [v0]",
	)
}
