// boilerplate generated by 'threeport-sdk gen' - do not edit

package django

import (
	api_v0 "django-threeport-module/pkg/api/v0"
	client_v0 "django-threeport-module/pkg/client/v0"
	"errors"
	"fmt"
	tpapi_lib "github.com/threeport/threeport/pkg/api/lib/v0"
	tpapi_v0 "github.com/threeport/threeport/pkg/api/v0"
	tpclient_lib "github.com/threeport/threeport/pkg/client/lib/v0"
	controller "github.com/threeport/threeport/pkg/controller/v0"
	event "github.com/threeport/threeport/pkg/event/v0"
	notifications "github.com/threeport/threeport/pkg/notifications/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"
)

// DjangoDefinitionReconciler reconciles system state when a DjangoDefinition
// is created, updated or deleted.
func DjangoDefinitionReconciler(r *controller.Reconciler) {
	r.ShutdownWait.Add(1)
	reconcilerLog := r.Log.WithValues("reconcilerName", r.Name)
	reconcilerLog.Info("reconciler started")
	shutdown := false

	// create a channel to receive OS signals
	osSignals := make(chan os.Signal, 1)
	lockReleased := make(chan bool, 1)

	// register the os signals channel to receive SIGINT and SIGTERM signals
	signal.Notify(osSignals, syscall.SIGINT, syscall.SIGTERM)

	for {
		// create a fresh log object per reconciliation loop so we don't
		// accumulate values across multiple loops
		log := r.Log.WithValues("reconcilerName", r.Name)

		if shutdown {
			break
		}

		// check for shutdown instruction
		select {
		case <-r.Shutdown:
			shutdown = true
		default:
			// pull message off queue
			msg := r.PullMessage()
			if msg == nil {
				continue
			}

			// consume message data to capture notification from API
			notif, err := notifications.ConsumeMessage(msg.Data)
			if err != nil {
				log.Error(
					err, "failed to consume message data from NATS",
					"msgData", string(msg.Data),
				)
				r.RequeueRaw(msg)
				log.V(1).Info("django definition reconciliation requeued with identical payload and fixed delay")
				continue
			}

			// determine the correct object version from the notification
			var djangoDefinition tpapi_lib.ReconciledThreeportApiObject
			switch notif.ObjectVersion {
			case "v0":
				djangoDefinition = &api_v0.DjangoDefinition{}
			default:
				log.Error(errors.New("received unrecognized version of django definition object"), "")
				r.RequeueRaw(msg)
				log.V(1).Info("django definition reconciliation requeued with identical payload and fixed delay")
				continue
			}

			// decode the object that was sent in the notification
			if err := djangoDefinition.DecodeNotifObject(notif.Object); err != nil {
				log.Error(err, "failed to marshal object map from consumed notification message")
				r.RequeueRaw(msg)
				log.V(1).Info("django definition reconciliation requeued with identical payload and fixed delay")
				continue
			}
			log = log.WithValues("djangoDefinitionID", djangoDefinition.GetId())

			// back off the requeue delay as needed
			requeueDelay := controller.SetRequeueDelay(
				notif.CreationTime,
			)

			// check for lock on object
			locked, ok := r.CheckLock(djangoDefinition)
			if locked || ok == false {
				r.Requeue(djangoDefinition, requeueDelay, msg)
				log.V(1).Info("django definition reconciliation requeued")
				continue
			}

			// set up handler to unlock and requeue on termination signal
			go func() {
				select {
				case <-osSignals:
					log.V(1).Info("received termination signal, performing unlock and requeue of django definition")
					r.UnlockAndRequeue(djangoDefinition, requeueDelay, lockReleased, msg)
				case <-lockReleased:
					log.V(1).Info("reached end of reconcile loop for django definition, closing out signal handler")
				}
			}()

			// put a lock on the reconciliation of the created object
			if ok := r.Lock(djangoDefinition); !ok {
				r.Requeue(djangoDefinition, requeueDelay, msg)
				log.V(1).Info("django definition reconciliation requeued")
				continue
			}

			// retrieve latest version of object
			var latestDjangoDefinition tpapi_lib.ReconciledThreeportApiObject
			var getLatestErr error
			switch notif.ObjectVersion {
			case "v0":
				latestObject, err := client_v0.GetDjangoDefinitionByID(
					r.APIClient,
					r.APIServer,
					djangoDefinition.GetId(),
				)
				latestDjangoDefinition = latestObject
				getLatestErr = err
			default:
				getLatestErr = errors.New("received unrecognized version of django definition object")
			}

			// check if error is 404 - if object no longer exists, no need to requeue
			if errors.Is(getLatestErr, tpclient_lib.ErrObjectNotFound) {
				log.Info("object no longer exists - halting reconciliation")
				r.ReleaseLock(djangoDefinition, lockReleased, msg, true)
				continue
			}
			if getLatestErr != nil {
				log.Error(getLatestErr, "failed to get django definition by ID from API")
				r.UnlockAndRequeue(djangoDefinition, requeueDelay, lockReleased, msg)
				continue
			}
			djangoDefinition = latestDjangoDefinition

			// determine which operation and act accordingly
			switch notif.Operation {
			case notifications.NotificationOperationCreated:
				if djangoDefinition.ScheduledForDeletion() != nil {
					log.Info("django definition scheduled for deletion - skipping create")
					break
				}
				// record in-progress before the custom handler so a later failure still has a start event
				progressNote := "creating"
				// type-assert so types without relationship-tagged foreign keys still emit creating
				if owner, ok := djangoDefinition.(tpapi_v0.RelationshipTaggedForeignKeyProvider); ok {
					progressNote = event.CreateNote(owner)
				}
				if recordErr := r.EventsRecorder.RecordEvent(
					&tpapi_v0.Event{
						Note:   util.Ptr(progressNote),
						Reason: util.Ptr(event.ReasonCreateInProgress),
						Type:   util.Ptr(event.TypeNormal),
					},
					djangoDefinition.GetId(),
					djangoDefinition.GetFullyQualifiedType(),
				); recordErr != nil {
					log.Error(recordErr, "failed to record in-progress event")
				}
				var operationErr error
				var customRequeueDelay int64
				switch djangoDefinition.GetVersion() {
				case "v0":
					requeueDelay, err := v0DjangoDefinitionCreated(
						r,
						djangoDefinition.(*api_v0.DjangoDefinition),
						&log,
					)
					customRequeueDelay = requeueDelay
					operationErr = err
				default:
					operationErr = errors.New("unrecognized version of django definition encountered for create operation")
				}
				if operationErr != nil {
					errorMsg := "failed to reconcile created django definition object"
					log.Error(operationErr, errorMsg)
					r.EventsRecorder.HandleEventOverride(
						&tpapi_v0.Event{
							Note:   util.Ptr(errorMsg),
							Reason: util.Ptr(event.ReasonCreateFailed),
							Type:   util.Ptr(event.TypeWarning),
						},
						djangoDefinition.GetId(),
						djangoDefinition.GetFullyQualifiedType(),
						operationErr,
						&log,
					)
					r.UnlockAndRequeue(
						djangoDefinition,
						requeueDelay,
						lockReleased,
						msg,
					)
					continue
				}
				if customRequeueDelay != 0 {
					log.Info("create requeued for future reconciliation")
					r.UnlockAndRequeue(
						djangoDefinition,
						customRequeueDelay,
						lockReleased,
						msg,
					)
					continue
				}
			case notifications.NotificationOperationUpdated:
				if djangoDefinition.ScheduledForDeletion() != nil {
					log.Info("django definition scheduled for deletion - skipping update")
					break
				}
				// record in-progress before the custom handler so a later failure still has a start event
				progressNote := event.UpdateNote()
				if recordErr := r.EventsRecorder.RecordEvent(
					&tpapi_v0.Event{
						Note:   util.Ptr(progressNote),
						Reason: util.Ptr(event.ReasonUpdateInProgress),
						Type:   util.Ptr(event.TypeNormal),
					},
					djangoDefinition.GetId(),
					djangoDefinition.GetFullyQualifiedType(),
				); recordErr != nil {
					log.Error(recordErr, "failed to record in-progress event")
				}
				var operationErr error
				var customRequeueDelay int64
				switch djangoDefinition.GetVersion() {
				case "v0":
					requeueDelay, err := v0DjangoDefinitionUpdated(
						r,
						djangoDefinition.(*api_v0.DjangoDefinition),
						&log,
					)
					customRequeueDelay = requeueDelay
					operationErr = err
				default:
					operationErr = errors.New("unrecognized version of django definition encountered for update operation")
				}
				if operationErr != nil {
					errorMsg := "failed to reconcile updated django definition object"
					log.Error(operationErr, errorMsg)
					r.EventsRecorder.HandleEventOverride(
						&tpapi_v0.Event{
							Note:   util.Ptr(errorMsg),
							Reason: util.Ptr(event.ReasonUpdateFailed),
							Type:   util.Ptr(event.TypeWarning),
						},
						djangoDefinition.GetId(),
						djangoDefinition.GetFullyQualifiedType(),
						operationErr,
						&log,
					)
					r.UnlockAndRequeue(
						djangoDefinition,
						requeueDelay,
						lockReleased,
						msg,
					)
					continue
				}
				if customRequeueDelay != 0 {
					log.Info("update requeued for future reconciliation")
					r.UnlockAndRequeue(
						djangoDefinition,
						customRequeueDelay,
						lockReleased,
						msg,
					)
					continue
				}
			case notifications.NotificationOperationDeleted:
				// record in-progress before the custom handler so a later failure still has a start event
				progressNote := "deleting"
				// type-assert so types without relationship-tagged foreign keys still emit deleting
				if owner, ok := djangoDefinition.(tpapi_v0.RelationshipTaggedForeignKeyProvider); ok {
					progressNote = event.DeleteNote(owner)
				}
				if recordErr := r.EventsRecorder.RecordEvent(
					&tpapi_v0.Event{
						Note:   util.Ptr(progressNote),
						Reason: util.Ptr(event.ReasonDeleteInProgress),
						Type:   util.Ptr(event.TypeNormal),
					},
					djangoDefinition.GetId(),
					djangoDefinition.GetFullyQualifiedType(),
				); recordErr != nil {
					log.Error(recordErr, "failed to record in-progress event")
				}
				var operationErr error
				var customRequeueDelay int64
				switch djangoDefinition.GetVersion() {
				case "v0":
					requeueDelay, err := v0DjangoDefinitionDeleted(
						r,
						djangoDefinition.(*api_v0.DjangoDefinition),
						&log,
					)
					customRequeueDelay = requeueDelay
					operationErr = err
				default:
					operationErr = errors.New("unrecognized version of django definition encountered for delete operation")
				}
				if operationErr != nil {
					if errors.Is(operationErr, tpclient_lib.ErrDeleteInProgress) || errors.Is(operationErr, tpclient_lib.ErrDeleteBlocked) {
						log.Info(
							"conflict reconciling deleted django definition object, requeueing",
							"cause", operationErr.Error(),
						)
						// in-progress event already recorded before the handler
						r.UnlockAndRequeue(
							djangoDefinition,
							int64(30),
							lockReleased,
							msg,
						)
						continue
					}
					errorMsg := "failed to reconcile deleted django definition object"
					log.Error(operationErr, errorMsg)
					r.EventsRecorder.HandleEventOverride(
						&tpapi_v0.Event{
							Note:   util.Ptr(errorMsg),
							Reason: util.Ptr(event.ReasonDeleteFailed),
							Type:   util.Ptr(event.TypeWarning),
						},
						djangoDefinition.GetId(),
						djangoDefinition.GetFullyQualifiedType(),
						operationErr,
						&log,
					)
					r.UnlockAndRequeue(
						djangoDefinition,
						requeueDelay,
						lockReleased,
						msg,
					)
					continue
				}
				if customRequeueDelay != 0 {
					log.Info("delete requeued for future reconciliation")
					r.UnlockAndRequeue(
						djangoDefinition,
						customRequeueDelay,
						lockReleased,
						msg,
					)
					continue
				}
				deletionTimestamp := util.Ptr(time.Now().UTC())
				deletedDjangoDefinition := api_v0.DjangoDefinition{
					Common: tpapi_v0.Common{ID: util.Ptr(djangoDefinition.GetId())},
					Reconciliation: tpapi_v0.Reconciliation{
						DeletionAcknowledged: deletionTimestamp,
						DeletionConfirmed:    deletionTimestamp,
						Reconciled:           util.Ptr(true),
					},
				}
				_, err = client_v0.UpdateDjangoDefinition(
					r.APIClient,
					r.APIServer,
					&deletedDjangoDefinition,
				)
				if err != nil {
					log.Error(err, "failed to update django definition to mark as deleted")
					r.UnlockAndRequeue(djangoDefinition, requeueDelay, lockReleased, msg)
					continue
				}
				_, err = client_v0.DeleteDjangoDefinition(
					r.APIClient,
					r.APIServer,
					djangoDefinition.GetId(),
				)
				if err != nil {
					if errors.Is(err, tpclient_lib.ErrDeleteInProgress) || errors.Is(err, tpclient_lib.ErrDeleteBlocked) {
						log.Info(
							"conflict deleting django definition, requeueing",
							"cause", err.Error(),
						)
						// in-progress event already recorded before the handler
						r.UnlockAndRequeue(
							djangoDefinition,
							int64(30),
							lockReleased,
							msg,
						)
						continue
					}
					log.Error(err, "failed to delete django definition")
					r.UnlockAndRequeue(djangoDefinition, requeueDelay, lockReleased, msg)
					continue
				}
			default:
				log.Error(
					errors.New("unrecognized notifcation operation"),
					"notification included an invalid operation",
				)
				r.UnlockAndRequeue(
					djangoDefinition,
					requeueDelay,
					lockReleased,
					msg,
				)
				continue
			}

			// set the object's Reconciled field to true if not deleted
			if notif.Operation != notifications.NotificationOperationDeleted {
				reconciledDjangoDefinition := api_v0.DjangoDefinition{
					Common:         tpapi_v0.Common{ID: util.Ptr(djangoDefinition.GetId())},
					Reconciliation: tpapi_v0.Reconciliation{Reconciled: util.Ptr(true)},
				}
				updatedDjangoDefinition, err := client_v0.UpdateDjangoDefinition(
					r.APIClient,
					r.APIServer,
					&reconciledDjangoDefinition,
				)
				if err != nil {
					log.Error(err, "failed to update django definition to mark as reconciled")
					r.UnlockAndRequeue(djangoDefinition, requeueDelay, lockReleased, msg)
					continue
				}
				log.V(1).Info(
					"django definition marked as reconciled in API",
					"django definitionName", updatedDjangoDefinition.Name,
				)
			}

			// release the lock on the reconciliation of the created object
			if ok := r.ReleaseLock(djangoDefinition, lockReleased, msg, true); !ok {
				log.Error(errors.New("django definition remains locked - will unlock when TTL expires"), "")
			} else {
				log.V(1).Info("django definition unlocked")
			}

			// log and record event for successful reconciliation
			successMsg := fmt.Sprintf(
				"django definition successfully reconciled for %s operation",
				strings.ToLower(string(notif.Operation)),
			)
			if err := r.EventsRecorder.RecordEvent(
				&tpapi_v0.Event{
					Note:   util.Ptr(successMsg),
					Reason: util.Ptr(event.GetSuccessReasonForOperation(notif.Operation)),
					Type:   util.Ptr(event.TypeNormal),
				},
				djangoDefinition.GetId(),
				djangoDefinition.GetFullyQualifiedType(),
			); err != nil {
				log.Error(err, "failed to record event for successful django definition reconciliation")
			}
			log.Info(successMsg)
		}
	}

	r.Sub.Unsubscribe()
	reconcilerLog.Info("reconciler shutting down")
	r.ShutdownWait.Done()
}
