// boilerplate generated by 'threeport-sdk gen' - do not edit

package main

import (
	v0 "django-threeport-module/pkg/api/v0"
	migrationtest "github.com/threeport/threeport/pkg/migrationtest/v0"
	"testing"
)

// This test applies the scaffolding initial migration in sqlite and
// checks every persisted model has a table and matching columns.
// It is boilerplate so the model list stays in lockstep with
// DatabaseInitNames. 000001 is scaffolding and is not regenerated.

// persistedModels returns one instance of every model the API persists.
func persistedModels() []interface{} {
	return []interface{}{
		&v0.DjangoDefinition{},
		&v0.DjangoInstance{},
	}
}

// TestMigrationsCoverEveryPersistedModel asserts the schema the migration
// chain builds matches the columns every persisted model declares, reporting
// both fields left without a column and columns left without a field.
func TestMigrationsCoverEveryPersistedModel(t *testing.T) {
	migrationtest.AssertMigrationsCoverModels(t, "threeport_django_goose_db_version", persistedModels())
}
