// boilerplate generated by 'threeport-sdk gen' - do not edit

package v0

import (
	"bytes"
	v0 "django-threeport-module/pkg/api/v0"
	"encoding/json"
	"errors"
	"fmt"
	tpapiserver_lib "github.com/threeport/threeport/pkg/api-server/lib/v0"
	tpclient_lib "github.com/threeport/threeport/pkg/client/lib/v0"
	tputil "github.com/threeport/threeport/pkg/util/v0"
	"net/http"
)

// GetDjangoDefinitions fetches all django definitions.
func GetDjangoDefinitions(apiClient *http.Client, apiAddr string) (*[]v0.DjangoDefinition, error) {
	var djangoDefinitions []v0.DjangoDefinition

	allPagesReceived := false
	var allPageData []tpapiserver_lib.Object
	nextCursor := uint(0)
	queryId := ""
	for !allPagesReceived {
		url := fmt.Sprintf("%s%s", apiAddr, v0.PathDjangoDefinitions)
		if queryId != "" {
			url = fmt.Sprintf("%s%s?queryid=%s&cursor=%d", apiAddr, v0.PathDjangoDefinitions, queryId, nextCursor)
		}

		response, err := tpclient_lib.GetResponse(
			apiClient,
			url,
			http.MethodGet,
			new(bytes.Buffer),
			map[string]string{},
			http.StatusOK,
		)
		if err != nil {
			return &djangoDefinitions, fmt.Errorf("call to threeport API returned unexpected response: %w", err)
		}

		allPageData = append(allPageData, response.Data...)

		if response.Meta.Pagination.HasMore {
			nextCursor = response.Meta.Pagination.NextCursor
			queryId = response.Meta.Pagination.QueryId
		} else {
			allPagesReceived = true
		}
	}

	jsonData, err := json.Marshal(allPageData)
	if err != nil {
		return &djangoDefinitions, fmt.Errorf("failed to marshal response data from threeport API: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(jsonData))
	decoder.UseNumber()
	if err := decoder.Decode(&djangoDefinitions); err != nil {
		return nil, fmt.Errorf("failed to decode object in response data from threeport API: %w", err)
	}

	return &djangoDefinitions, nil
}

// GetDjangoDefinitionByID fetches a django definition by ID.
func GetDjangoDefinitionByID(apiClient *http.Client, apiAddr string, id uint) (*v0.DjangoDefinition, error) {
	var djangoDefinition v0.DjangoDefinition

	response, err := tpclient_lib.GetResponse(
		apiClient,
		fmt.Sprintf("%s%s/%d", apiAddr, v0.PathDjangoDefinitions, id),
		http.MethodGet,
		new(bytes.Buffer),
		map[string]string{},
		http.StatusOK,
	)
	if err != nil {
		return &djangoDefinition, fmt.Errorf("call to threeport API returned unexpected response: %w", err)
	}

	if len(response.Data) == 0 {
		return &djangoDefinition, errors.New("threeport API returned no object in response data")
	}

	jsonData, err := json.Marshal(response.Data[0])
	if err != nil {
		return &djangoDefinition, fmt.Errorf("failed to marshal response data from threeport API: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(jsonData))
	decoder.UseNumber()
	if err := decoder.Decode(&djangoDefinition); err != nil {
		return nil, fmt.Errorf("failed to decode object in response data from threeport API: %w", err)
	}

	return &djangoDefinition, nil
}

// GetDjangoDefinitionsByQueryString fetches django definitions by provided query string.
func GetDjangoDefinitionsByQueryString(apiClient *http.Client, apiAddr string, queryString string) (*[]v0.DjangoDefinition, error) {
	var djangoDefinitions []v0.DjangoDefinition

	response, err := tpclient_lib.GetResponse(
		apiClient,
		fmt.Sprintf("%s%s?%s", apiAddr, v0.PathDjangoDefinitions, queryString),
		http.MethodGet,
		new(bytes.Buffer),
		map[string]string{},
		http.StatusOK,
	)
	if err != nil {
		return &djangoDefinitions, fmt.Errorf("call to threeport API returned unexpected response: %w", err)
	}

	jsonData, err := json.Marshal(response.Data)
	if err != nil {
		return &djangoDefinitions, fmt.Errorf("failed to marshal response data from threeport API: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(jsonData))
	decoder.UseNumber()
	if err := decoder.Decode(&djangoDefinitions); err != nil {
		return nil, fmt.Errorf("failed to decode object in response data from threeport API: %w", err)
	}

	return &djangoDefinitions, nil
}

// GetDjangoDefinitionByName fetches a django definition by name.
func GetDjangoDefinitionByName(apiClient *http.Client, apiAddr, name string) (*v0.DjangoDefinition, error) {
	var djangoDefinitions []v0.DjangoDefinition

	response, err := tpclient_lib.GetResponse(
		apiClient,
		fmt.Sprintf("%s%s?name=%s", apiAddr, v0.PathDjangoDefinitions, name),
		http.MethodGet,
		new(bytes.Buffer),
		map[string]string{},
		http.StatusOK,
	)
	if err != nil {
		return &v0.DjangoDefinition{}, fmt.Errorf("call to threeport API returned unexpected response: %w", err)
	}

	jsonData, err := json.Marshal(response.Data)
	if err != nil {
		return &v0.DjangoDefinition{}, fmt.Errorf("failed to marshal response data from threeport API: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(jsonData))
	decoder.UseNumber()
	if err := decoder.Decode(&djangoDefinitions); err != nil {
		return nil, fmt.Errorf("failed to decode object in response data from threeport API: %w", err)
	}

	switch {
	case len(djangoDefinitions) < 1:
		return &v0.DjangoDefinition{}, tpclient_lib.ErrObjectNotFound
	case len(djangoDefinitions) > 1:
		return &v0.DjangoDefinition{}, fmt.Errorf("more than one django definition with name %s returned", name)
	}

	return &djangoDefinitions[0], nil
}

// CreateDjangoDefinition creates a new django definition.
func CreateDjangoDefinition(apiClient *http.Client, apiAddr string, djangoDefinition *v0.DjangoDefinition) (*v0.DjangoDefinition, error) {
	tpclient_lib.ReplaceAssociatedObjectsWithNil(djangoDefinition)
	jsonDjangoDefinition, err := tputil.MarshalObject(djangoDefinition)
	if err != nil {
		return djangoDefinition, fmt.Errorf("failed to marshal provided object to JSON: %w", err)
	}

	response, err := tpclient_lib.GetResponse(
		apiClient,
		fmt.Sprintf("%s%s", apiAddr, v0.PathDjangoDefinitions),
		http.MethodPost,
		bytes.NewBuffer(jsonDjangoDefinition),
		map[string]string{},
		http.StatusCreated,
	)
	if err != nil {
		return djangoDefinition, fmt.Errorf("call to threeport API returned unexpected response: %w", err)
	}

	if len(response.Data) == 0 {
		return djangoDefinition, errors.New("threeport API returned no object in response data")
	}

	jsonData, err := json.Marshal(response.Data[0])
	if err != nil {
		return djangoDefinition, fmt.Errorf("failed to marshal response data from threeport API: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(jsonData))
	decoder.UseNumber()
	if err := decoder.Decode(&djangoDefinition); err != nil {
		return nil, fmt.Errorf("failed to decode object in response data from threeport API: %w", err)
	}

	return djangoDefinition, nil
}

// UpdateDjangoDefinition updates a django definition with a PATCH request.
func UpdateDjangoDefinition(apiClient *http.Client, apiAddr string, djangoDefinition *v0.DjangoDefinition) (*v0.DjangoDefinition, error) {
	tpclient_lib.ReplaceAssociatedObjectsWithNil(djangoDefinition)
	// capture the object ID, make a copy of the object, then remove fields that
	// cannot be updated in the API
	djangoDefinitionID := *djangoDefinition.ID
	payloadDjangoDefinition := *djangoDefinition
	payloadDjangoDefinition.ID = nil
	payloadDjangoDefinition.CreatedAt = nil
	payloadDjangoDefinition.UpdatedAt = nil

	jsonDjangoDefinition, err := tputil.MarshalObject(payloadDjangoDefinition)
	if err != nil {
		return djangoDefinition, fmt.Errorf("failed to marshal provided object to JSON: %w", err)
	}

	response, err := tpclient_lib.GetResponse(
		apiClient,
		fmt.Sprintf("%s%s/%d", apiAddr, v0.PathDjangoDefinitions, djangoDefinitionID),
		http.MethodPatch,
		bytes.NewBuffer(jsonDjangoDefinition),
		map[string]string{},
		http.StatusOK,
	)
	if err != nil {
		return djangoDefinition, fmt.Errorf("call to threeport API returned unexpected response: %w", err)
	}

	if len(response.Data) == 0 {
		return djangoDefinition, errors.New("threeport API returned no object in response data")
	}

	jsonData, err := json.Marshal(response.Data[0])
	if err != nil {
		return djangoDefinition, fmt.Errorf("failed to marshal response data from threeport API: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(jsonData))
	decoder.UseNumber()
	if err := decoder.Decode(&payloadDjangoDefinition); err != nil {
		return nil, fmt.Errorf("failed to decode object in response data from threeport API: %w", err)
	}

	payloadDjangoDefinition.ID = &djangoDefinitionID
	return &payloadDjangoDefinition, nil
}

// ReplaceDjangoDefinition updates a django definition with a PUT request.
func ReplaceDjangoDefinition(apiClient *http.Client, apiAddr string, djangoDefinition *v0.DjangoDefinition) (*v0.DjangoDefinition, error) {
	tpclient_lib.ReplaceAssociatedObjectsWithNil(djangoDefinition)
	// capture the object ID, make a copy of the object, then remove fields that
	// cannot be updated in the API
	djangoDefinitionID := *djangoDefinition.ID
	payloadDjangoDefinition := *djangoDefinition
	payloadDjangoDefinition.ID = nil
	payloadDjangoDefinition.CreatedAt = nil
	payloadDjangoDefinition.UpdatedAt = nil

	jsonDjangoDefinition, err := tputil.MarshalObject(payloadDjangoDefinition)
	if err != nil {
		return djangoDefinition, fmt.Errorf("failed to marshal provided object to JSON: %w", err)
	}

	response, err := tpclient_lib.GetResponse(
		apiClient,
		fmt.Sprintf("%s%s/%d", apiAddr, v0.PathDjangoDefinitions, djangoDefinitionID),
		http.MethodPut,
		bytes.NewBuffer(jsonDjangoDefinition),
		map[string]string{},
		http.StatusOK,
	)
	if err != nil {
		return djangoDefinition, fmt.Errorf("call to threeport API returned unexpected response: %w", err)
	}

	if len(response.Data) == 0 {
		return djangoDefinition, errors.New("threeport API returned no object in response data")
	}

	jsonData, err := json.Marshal(response.Data[0])
	if err != nil {
		return djangoDefinition, fmt.Errorf("failed to marshal response data from threeport API: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(jsonData))
	decoder.UseNumber()
	if err := decoder.Decode(&payloadDjangoDefinition); err != nil {
		return nil, fmt.Errorf("failed to decode object in response data from threeport API: %w", err)
	}

	payloadDjangoDefinition.ID = &djangoDefinitionID
	return &payloadDjangoDefinition, nil
}

// DeleteDjangoDefinition deletes a django definition by ID.
func DeleteDjangoDefinition(apiClient *http.Client, apiAddr string, id uint) (*v0.DjangoDefinition, error) {
	var djangoDefinition v0.DjangoDefinition

	response, err := tpclient_lib.GetResponse(
		apiClient,
		fmt.Sprintf("%s%s/%d", apiAddr, v0.PathDjangoDefinitions, id),
		http.MethodDelete,
		new(bytes.Buffer),
		map[string]string{},
		http.StatusOK,
	)
	if err != nil {
		return &djangoDefinition, fmt.Errorf("call to threeport API returned unexpected response: %w", err)
	}

	if len(response.Data) == 0 {
		return &djangoDefinition, errors.New("threeport API returned no object in response data")
	}

	jsonData, err := json.Marshal(response.Data[0])
	if err != nil {
		return &djangoDefinition, fmt.Errorf("failed to marshal response data from threeport API: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(jsonData))
	decoder.UseNumber()
	if err := decoder.Decode(&djangoDefinition); err != nil {
		return nil, fmt.Errorf("failed to decode object in response data from threeport API: %w", err)
	}

	return &djangoDefinition, nil
}

// GetDjangoInstances fetches all django instances.
func GetDjangoInstances(apiClient *http.Client, apiAddr string) (*[]v0.DjangoInstance, error) {
	var djangoInstances []v0.DjangoInstance

	allPagesReceived := false
	var allPageData []tpapiserver_lib.Object
	nextCursor := uint(0)
	queryId := ""
	for !allPagesReceived {
		url := fmt.Sprintf("%s%s", apiAddr, v0.PathDjangoInstances)
		if queryId != "" {
			url = fmt.Sprintf("%s%s?queryid=%s&cursor=%d", apiAddr, v0.PathDjangoInstances, queryId, nextCursor)
		}

		response, err := tpclient_lib.GetResponse(
			apiClient,
			url,
			http.MethodGet,
			new(bytes.Buffer),
			map[string]string{},
			http.StatusOK,
		)
		if err != nil {
			return &djangoInstances, fmt.Errorf("call to threeport API returned unexpected response: %w", err)
		}

		allPageData = append(allPageData, response.Data...)

		if response.Meta.Pagination.HasMore {
			nextCursor = response.Meta.Pagination.NextCursor
			queryId = response.Meta.Pagination.QueryId
		} else {
			allPagesReceived = true
		}
	}

	jsonData, err := json.Marshal(allPageData)
	if err != nil {
		return &djangoInstances, fmt.Errorf("failed to marshal response data from threeport API: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(jsonData))
	decoder.UseNumber()
	if err := decoder.Decode(&djangoInstances); err != nil {
		return nil, fmt.Errorf("failed to decode object in response data from threeport API: %w", err)
	}

	return &djangoInstances, nil
}

// GetDjangoInstanceByID fetches a django instance by ID.
func GetDjangoInstanceByID(apiClient *http.Client, apiAddr string, id uint) (*v0.DjangoInstance, error) {
	var djangoInstance v0.DjangoInstance

	response, err := tpclient_lib.GetResponse(
		apiClient,
		fmt.Sprintf("%s%s/%d", apiAddr, v0.PathDjangoInstances, id),
		http.MethodGet,
		new(bytes.Buffer),
		map[string]string{},
		http.StatusOK,
	)
	if err != nil {
		return &djangoInstance, fmt.Errorf("call to threeport API returned unexpected response: %w", err)
	}

	if len(response.Data) == 0 {
		return &djangoInstance, errors.New("threeport API returned no object in response data")
	}

	jsonData, err := json.Marshal(response.Data[0])
	if err != nil {
		return &djangoInstance, fmt.Errorf("failed to marshal response data from threeport API: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(jsonData))
	decoder.UseNumber()
	if err := decoder.Decode(&djangoInstance); err != nil {
		return nil, fmt.Errorf("failed to decode object in response data from threeport API: %w", err)
	}

	return &djangoInstance, nil
}

// GetDjangoInstancesByQueryString fetches django instances by provided query string.
func GetDjangoInstancesByQueryString(apiClient *http.Client, apiAddr string, queryString string) (*[]v0.DjangoInstance, error) {
	var djangoInstances []v0.DjangoInstance

	response, err := tpclient_lib.GetResponse(
		apiClient,
		fmt.Sprintf("%s%s?%s", apiAddr, v0.PathDjangoInstances, queryString),
		http.MethodGet,
		new(bytes.Buffer),
		map[string]string{},
		http.StatusOK,
	)
	if err != nil {
		return &djangoInstances, fmt.Errorf("call to threeport API returned unexpected response: %w", err)
	}

	jsonData, err := json.Marshal(response.Data)
	if err != nil {
		return &djangoInstances, fmt.Errorf("failed to marshal response data from threeport API: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(jsonData))
	decoder.UseNumber()
	if err := decoder.Decode(&djangoInstances); err != nil {
		return nil, fmt.Errorf("failed to decode object in response data from threeport API: %w", err)
	}

	return &djangoInstances, nil
}

// GetDjangoInstanceByName fetches a django instance by name.
func GetDjangoInstanceByName(apiClient *http.Client, apiAddr, name string) (*v0.DjangoInstance, error) {
	var djangoInstances []v0.DjangoInstance

	response, err := tpclient_lib.GetResponse(
		apiClient,
		fmt.Sprintf("%s%s?name=%s", apiAddr, v0.PathDjangoInstances, name),
		http.MethodGet,
		new(bytes.Buffer),
		map[string]string{},
		http.StatusOK,
	)
	if err != nil {
		return &v0.DjangoInstance{}, fmt.Errorf("call to threeport API returned unexpected response: %w", err)
	}

	jsonData, err := json.Marshal(response.Data)
	if err != nil {
		return &v0.DjangoInstance{}, fmt.Errorf("failed to marshal response data from threeport API: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(jsonData))
	decoder.UseNumber()
	if err := decoder.Decode(&djangoInstances); err != nil {
		return nil, fmt.Errorf("failed to decode object in response data from threeport API: %w", err)
	}

	switch {
	case len(djangoInstances) < 1:
		return &v0.DjangoInstance{}, tpclient_lib.ErrObjectNotFound
	case len(djangoInstances) > 1:
		return &v0.DjangoInstance{}, fmt.Errorf("more than one django instance with name %s returned", name)
	}

	return &djangoInstances[0], nil
}

// CreateDjangoInstance creates a new django instance.
func CreateDjangoInstance(apiClient *http.Client, apiAddr string, djangoInstance *v0.DjangoInstance) (*v0.DjangoInstance, error) {
	tpclient_lib.ReplaceAssociatedObjectsWithNil(djangoInstance)
	jsonDjangoInstance, err := tputil.MarshalObject(djangoInstance)
	if err != nil {
		return djangoInstance, fmt.Errorf("failed to marshal provided object to JSON: %w", err)
	}

	response, err := tpclient_lib.GetResponse(
		apiClient,
		fmt.Sprintf("%s%s", apiAddr, v0.PathDjangoInstances),
		http.MethodPost,
		bytes.NewBuffer(jsonDjangoInstance),
		map[string]string{},
		http.StatusCreated,
	)
	if err != nil {
		return djangoInstance, fmt.Errorf("call to threeport API returned unexpected response: %w", err)
	}

	if len(response.Data) == 0 {
		return djangoInstance, errors.New("threeport API returned no object in response data")
	}

	jsonData, err := json.Marshal(response.Data[0])
	if err != nil {
		return djangoInstance, fmt.Errorf("failed to marshal response data from threeport API: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(jsonData))
	decoder.UseNumber()
	if err := decoder.Decode(&djangoInstance); err != nil {
		return nil, fmt.Errorf("failed to decode object in response data from threeport API: %w", err)
	}

	return djangoInstance, nil
}

// UpdateDjangoInstance updates a django instance with a PATCH request.
func UpdateDjangoInstance(apiClient *http.Client, apiAddr string, djangoInstance *v0.DjangoInstance) (*v0.DjangoInstance, error) {
	tpclient_lib.ReplaceAssociatedObjectsWithNil(djangoInstance)
	// capture the object ID, make a copy of the object, then remove fields that
	// cannot be updated in the API
	djangoInstanceID := *djangoInstance.ID
	payloadDjangoInstance := *djangoInstance
	payloadDjangoInstance.ID = nil
	payloadDjangoInstance.CreatedAt = nil
	payloadDjangoInstance.UpdatedAt = nil

	jsonDjangoInstance, err := tputil.MarshalObject(payloadDjangoInstance)
	if err != nil {
		return djangoInstance, fmt.Errorf("failed to marshal provided object to JSON: %w", err)
	}

	response, err := tpclient_lib.GetResponse(
		apiClient,
		fmt.Sprintf("%s%s/%d", apiAddr, v0.PathDjangoInstances, djangoInstanceID),
		http.MethodPatch,
		bytes.NewBuffer(jsonDjangoInstance),
		map[string]string{},
		http.StatusOK,
	)
	if err != nil {
		return djangoInstance, fmt.Errorf("call to threeport API returned unexpected response: %w", err)
	}

	if len(response.Data) == 0 {
		return djangoInstance, errors.New("threeport API returned no object in response data")
	}

	jsonData, err := json.Marshal(response.Data[0])
	if err != nil {
		return djangoInstance, fmt.Errorf("failed to marshal response data from threeport API: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(jsonData))
	decoder.UseNumber()
	if err := decoder.Decode(&payloadDjangoInstance); err != nil {
		return nil, fmt.Errorf("failed to decode object in response data from threeport API: %w", err)
	}

	payloadDjangoInstance.ID = &djangoInstanceID
	return &payloadDjangoInstance, nil
}

// ReplaceDjangoInstance updates a django instance with a PUT request.
func ReplaceDjangoInstance(apiClient *http.Client, apiAddr string, djangoInstance *v0.DjangoInstance) (*v0.DjangoInstance, error) {
	tpclient_lib.ReplaceAssociatedObjectsWithNil(djangoInstance)
	// capture the object ID, make a copy of the object, then remove fields that
	// cannot be updated in the API
	djangoInstanceID := *djangoInstance.ID
	payloadDjangoInstance := *djangoInstance
	payloadDjangoInstance.ID = nil
	payloadDjangoInstance.CreatedAt = nil
	payloadDjangoInstance.UpdatedAt = nil

	jsonDjangoInstance, err := tputil.MarshalObject(payloadDjangoInstance)
	if err != nil {
		return djangoInstance, fmt.Errorf("failed to marshal provided object to JSON: %w", err)
	}

	response, err := tpclient_lib.GetResponse(
		apiClient,
		fmt.Sprintf("%s%s/%d", apiAddr, v0.PathDjangoInstances, djangoInstanceID),
		http.MethodPut,
		bytes.NewBuffer(jsonDjangoInstance),
		map[string]string{},
		http.StatusOK,
	)
	if err != nil {
		return djangoInstance, fmt.Errorf("call to threeport API returned unexpected response: %w", err)
	}

	if len(response.Data) == 0 {
		return djangoInstance, errors.New("threeport API returned no object in response data")
	}

	jsonData, err := json.Marshal(response.Data[0])
	if err != nil {
		return djangoInstance, fmt.Errorf("failed to marshal response data from threeport API: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(jsonData))
	decoder.UseNumber()
	if err := decoder.Decode(&payloadDjangoInstance); err != nil {
		return nil, fmt.Errorf("failed to decode object in response data from threeport API: %w", err)
	}

	payloadDjangoInstance.ID = &djangoInstanceID
	return &payloadDjangoInstance, nil
}

// DeleteDjangoInstance deletes a django instance by ID.
func DeleteDjangoInstance(apiClient *http.Client, apiAddr string, id uint) (*v0.DjangoInstance, error) {
	var djangoInstance v0.DjangoInstance

	response, err := tpclient_lib.GetResponse(
		apiClient,
		fmt.Sprintf("%s%s/%d", apiAddr, v0.PathDjangoInstances, id),
		http.MethodDelete,
		new(bytes.Buffer),
		map[string]string{},
		http.StatusOK,
	)
	if err != nil {
		return &djangoInstance, fmt.Errorf("call to threeport API returned unexpected response: %w", err)
	}

	if len(response.Data) == 0 {
		return &djangoInstance, errors.New("threeport API returned no object in response data")
	}

	jsonData, err := json.Marshal(response.Data[0])
	if err != nil {
		return &djangoInstance, fmt.Errorf("failed to marshal response data from threeport API: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(jsonData))
	decoder.UseNumber()
	if err := decoder.Decode(&djangoInstance); err != nil {
		return nil, fmt.Errorf("failed to decode object in response data from threeport API: %w", err)
	}

	return &djangoInstance, nil
}
