// boilerplate generated by 'threeport-sdk gen' - do not edit

package handlers

import (
	notif "django-threeport-module/internal/django/notif"
	api_v0 "django-threeport-module/pkg/api/v0"
	"errors"
	"fmt"
	echo "github.com/labstack/echo/v4"
	tpapiserver_lib "github.com/threeport/threeport/pkg/api-server/lib/v0"
	tphandlers_v0 "github.com/threeport/threeport/pkg/api-server/v0/handlers"
	tpapi_v0 "github.com/threeport/threeport/pkg/api/v0"
	notifications "github.com/threeport/threeport/pkg/notifications/v0"
	tputil_v0 "github.com/threeport/threeport/pkg/util/v0"
	zap "go.uber.org/zap"
	gorm "gorm.io/gorm"
	"net/http"
	"time"
)

///////////////////////////////////////////////////////////////////////////////
// DjangoDefinition
///////////////////////////////////////////////////////////////////////////////

// @Summary GetDjangoDefinitionVersions gets the supported versions for the django definition API.
// @Description Get the supported API versions for django definitions.
// @ID djangoDefinition-get-versions
// @Produce json
// @Success 200 {object} tpapiserver_lib.ApiObjectVersions "OK"
// @Router /threeport-io/django-definitions/versions [GET]
func (h Handler) GetDjangoDefinitionVersions(c echo.Context) error {
	return c.JSON(http.StatusOK, tpapiserver_lib.ObjectVersions[string(api_v0.ObjectTypeDjangoDefinition)])
}

// @Summary adds a new django definition.
// @Description Add a new django definition to the Threeport database.
// @ID add-v0-djangoDefinition
// @Accept json
// @Produce json
// @Param djangoDefinition body api_v0.DjangoDefinition true "DjangoDefinition object"
// @Success 201 {object} v0.Response "Created"
// @Failure 400 {object} v0.Response "Bad Request"
// @Failure 409 {object} v0.Response "Conflict"
// @Failure 500 {object} v0.Response "Internal Server Error"
// @Router /threeport-io/v0/django-definitions [POST]
func (h Handler) AddDjangoDefinition(c echo.Context) error {
	objectType := api_v0.ObjectTypeDjangoDefinition
	fullyQualifiedType := new(api_v0.DjangoDefinition).GetFullyQualifiedType()
	var djangoDefinition api_v0.DjangoDefinition

	// check for empty payload, unsupported fields, GORM Model fields, optional associations, etc.
	if id, err := tpapiserver_lib.PayloadCheck(c, true, false, objectType, djangoDefinition); err != nil {
		h.Handler.Logger.Error("handler error: error performing payload check", zap.Error(err))
		return tpapiserver_lib.ResponseStatusErr(id, c, nil, errors.New(err.Error()), fullyQualifiedType)
	}

	if err := c.Bind(&djangoDefinition); err != nil {
		h.Handler.Logger.Error("handler error: error binding object", zap.Error(err))
		return tpapiserver_lib.ResponseStatusBindErr(c, nil, err, fullyQualifiedType)
	}

	// check for missing required fields
	if id, err := tpapiserver_lib.ValidateBoundData(c, djangoDefinition, objectType); err != nil {
		h.Handler.Logger.Error("handler error: error validating bound data", zap.Error(err))
		return tpapiserver_lib.ResponseStatusErr(id, c, nil, errors.New(err.Error()), fullyQualifiedType)
	}

	// persist to DB
	if result := h.Handler.Write(c, func(db *gorm.DB) *gorm.DB {
		// clear id so a retried create does not reuse a rolled-back key
		djangoDefinition.ID = nil
		return db.Create(&djangoDefinition)
	}); result.Error != nil {
		h.Handler.Logger.Error("handler error: error creating object", zap.Error(result.Error))
		// check if this is a custom HTTP error with specific status code
		var httpErr *tputil_v0.HttpError
		if errors.As(result.Error, &httpErr) {
			return tpapiserver_lib.ResponseStatusErr(
				httpErr.GetStatusCode(), c, nil, result.Error, fullyQualifiedType,
			)
		}
		return tpapiserver_lib.RespondWriteError(
			c,
			h.Handler.Logger,
			result.Error,
			new(api_v0.DjangoDefinition),
			fullyQualifiedType,
		)
	}

	// the write has committed; bring any process state that mirrors the
	// database in line before answering, so a caller that gets a 200 can
	// rely on it. A persist hook cannot do this: it runs inside the
	// transaction, so it would act on a write that may never commit.
	if err := tpapiserver_lib.AfterCommitCreate(h.Handler.DB, &djangoDefinition); err != nil {
		h.Handler.Logger.Error("handler error: error reconciling process state after commit", zap.Error(err))
		return tpapiserver_lib.ResponseStatus500(c, nil, err, fullyQualifiedType)
	}

	// notify controller if reconciliation is required
	if !*djangoDefinition.Reconciled {
		notifPayload, err := djangoDefinition.NotificationPayload(
			notifications.NotificationOperationCreated,
			false,
			time.Now().Unix(),
		)
		if err != nil {
			h.Handler.Logger.Error("handler error: error creating NATS notification", zap.Error(err))
			return tpapiserver_lib.ResponseStatus500(c, nil, err, fullyQualifiedType)
		}
		h.Handler.JS.Publish(notif.DjangoDefinitionCreateSubject, *notifPayload)
	}

	response, err := tpapiserver_lib.CreateResponse(
		tpapiserver_lib.SingleObjectMeta(),
		djangoDefinition,
		fullyQualifiedType,
	)
	if err != nil {
		h.Handler.Logger.Error("handler error: error creating response", zap.Error(err))
		return tpapiserver_lib.ResponseStatus500(c, nil, err, fullyQualifiedType)
	}

	return tpapiserver_lib.ResponseStatus201(c, *response)
}

// @Summary gets all django definitions.
// @Description Get all django definitions from the Threeport database.
// @ID get-v0-djangoDefinitions
// @Accept json
// @Produce json
// @Param name query string false "filter by exact django definition name (case sensitive)"
// @Success 200 {object} v0.Response "OK"
// @Failure 400 {object} v0.Response "Bad Request"
// @Failure 500 {object} v0.Response "Internal Server Error"
// @Router /threeport-io/v0/django-definitions [GET]
func (h Handler) GetDjangoDefinitions(c echo.Context) error {
	fullyQualifiedType := new(api_v0.DjangoDefinition).GetFullyQualifiedType()

	// get pagination parameters
	pageParams, err := c.(*tpapiserver_lib.CustomContext).GetPaginationParams()
	if err != nil {
		return tpapiserver_lib.ResponseStatus400(c, pageParams, err, fullyQualifiedType)
	}

	// bind filter
	var filter api_v0.DjangoDefinition
	if err := c.Bind(&filter); err != nil {
		h.Handler.Logger.Error("handler error: error binding filter", zap.Error(err))
		return tpapiserver_lib.ResponseStatus400(c, pageParams, err, fullyQualifiedType)
	}

	pagination := new(tpapiserver_lib.Pagination)
	pagination.Limit = pageParams.Limit

	records := &[]api_v0.DjangoDefinition{}
	var returnedCount int64

	switch {
	case pageParams.QueryId == "":
		// no query ID provided, so the client is not requesting a specific page of results
		// count total number of objects
		var totalCount int64
		if result := h.Handler.RequestDB(c).Model(&api_v0.DjangoDefinition{}).Where(&filter).Count(&totalCount); result.Error != nil {
			h.Handler.Logger.Error("handler error: error counting objects", zap.Error(result.Error))
			return tpapiserver_lib.ResponseStatus500(c, pageParams, result.Error, fullyQualifiedType)
		}

		// see if total count is greater than the limit
		pagination.HasMore = totalCount > pagination.Limit

		switch pagination.HasMore {
		case false:
			// if we don't have to paginate, return all records
			if result := h.Handler.RequestDB(c).Order("ID asc").Where(&filter).Find(records); result.Error != nil {
				h.Handler.Logger.Error("handler error: error finding objects", zap.Error(result.Error))
				return tpapiserver_lib.ResponseStatus500(c, pageParams, result.Error, fullyQualifiedType)
			}
			returnedCount = int64(len(*records))
		case true:
			// dispatch to the configured pagination strategy to fetch the first page
			queryTable := filter.TableName()
			queryId, count, err := h.Handler.DispatchGetPaginatedRecords(h.Handler.RequestDB(c).Model(&api_v0.DjangoDefinition{}).Where(&filter), records, queryTable, pageParams)
			if err != nil {
				if errors.Is(err, tpapiserver_lib.ErrInvalidPaginationQueryId) || errors.Is(err, tpapiserver_lib.ErrPaginationSessionExpired) {
					return tpapiserver_lib.ResponseStatus400(c, pageParams, err, fullyQualifiedType)
				}
				h.Handler.Logger.Error("handler error: error fetching paginated records", zap.Error(err))
				return tpapiserver_lib.ResponseStatus500(c, pageParams, err, fullyQualifiedType)
			}
			pagination.QueryId = queryId
			returnedCount = count

			// set the cursor for the next page of results
			if len(*records) > 0 {
				pagination.NextCursor = *(*records)[len(*records)-1].ID
			} else {
				pagination.NextCursor = 0
			}
		}
	case pageParams.QueryId != "" && pageParams.Cursor == 0:
		// client provided a query ID but no cursor, so we cannot fetch the next page of results
		return tpapiserver_lib.ResponseStatus400(c, pageParams, errors.New("cursor is required when query ID is provided"), fullyQualifiedType)
	case pageParams.QueryId != "" && pageParams.Cursor != 0:
		// continuation: dispatch to the configured pagination strategy to fetch the next page
		queryTable := filter.TableName()
		queryId, count, err := h.Handler.DispatchGetPaginatedRecords(h.Handler.RequestDB(c).Model(&api_v0.DjangoDefinition{}).Where(&filter), records, queryTable, pageParams)
		if err != nil {
			if errors.Is(err, tpapiserver_lib.ErrInvalidPaginationQueryId) || errors.Is(err, tpapiserver_lib.ErrPaginationSessionExpired) {
				return tpapiserver_lib.ResponseStatus400(c, pageParams, err, fullyQualifiedType)
			}
			h.Handler.Logger.Error("handler error: error fetching paginated records", zap.Error(err))
			return tpapiserver_lib.ResponseStatus500(c, pageParams, err, fullyQualifiedType)
		}
		pagination.QueryId = queryId
		returnedCount = count

		// set the cursor for the next page of results
		if len(*records) > 0 {
			pagination.NextCursor = *(*records)[len(*records)-1].ID
		} else {
			pagination.NextCursor = 0
		}

		// see if we fetched the last of the records
		pagination.HasMore = returnedCount >= pagination.Limit
	}

	// construct response
	response, err := tpapiserver_lib.CreateResponse(
		&tpapiserver_lib.Meta{
			ObjectCount: returnedCount,
			Pagination:  *pagination,
		},
		*records,
		fullyQualifiedType,
	)
	if err != nil {
		h.Handler.Logger.Error("handler error: error creating response", zap.Error(err))
		return tpapiserver_lib.ResponseStatus500(c, pageParams, err, fullyQualifiedType)
	}

	return tpapiserver_lib.ResponseStatus200(c, *response)
}

// @Summary gets a django definition.
// @Description Get a particular django definition from the database.
// @ID get-v0-djangoDefinition
// @Accept json
// @Produce json
// @Param id path int true "ID"
// @Success 200 {object} v0.Response "OK"
// @Failure 404 {object} v0.Response "Not Found"
// @Failure 500 {object} v0.Response "Internal Server Error"
// @Router /threeport-io/v0/django-definitions/{id} [GET]
func (h Handler) GetDjangoDefinition(c echo.Context) error {
	fullyQualifiedType := new(api_v0.DjangoDefinition).GetFullyQualifiedType()
	djangoDefinitionID := c.Param("id")
	var djangoDefinition api_v0.DjangoDefinition
	if result := h.Handler.RequestDB(c).
		First(&djangoDefinition, djangoDefinitionID); result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return tpapiserver_lib.ResponseStatus404(c, nil, result.Error, fullyQualifiedType)
		}
		h.Handler.Logger.Error("handler error: error finding object", zap.Error(result.Error))
		return tpapiserver_lib.ResponseStatus500(c, nil, result.Error, fullyQualifiedType)
	}

	response, err := tpapiserver_lib.CreateResponse(
		tpapiserver_lib.SingleObjectMeta(),
		djangoDefinition,
		fullyQualifiedType,
	)
	if err != nil {
		h.Handler.Logger.Error("handler error: error creating response", zap.Error(err))
		return tpapiserver_lib.ResponseStatus500(c, nil, err, fullyQualifiedType)
	}

	return tpapiserver_lib.ResponseStatus200(c, *response)
}

// @Summary updates specific fields for an existing django definition.
// @Description Update a django definition in the database.  Provide one or more fields to update.
// @Description Note: This API endpint is for updating django definition objects only.
// @Description Request bodies that include related objects will be accepted, however
// @Description the related objects will not be changed.  Call the patch or put method for
// @Description each particular existing object to change them.
// @ID update-v0-djangoDefinition
// @Accept json
// @Produce json
// @Param id path int true "ID"
// @Param djangoDefinition body api_v0.DjangoDefinition true "DjangoDefinition object"
// @Success 200 {object} v0.Response "OK"
// @Failure 400 {object} v0.Response "Bad Request"
// @Failure 404 {object} v0.Response "Not Found"
// @Failure 409 {object} v0.Response "Conflict"
// @Failure 500 {object} v0.Response "Internal Server Error"
// @Router /threeport-io/v0/django-definitions/{id} [PATCH]
func (h Handler) UpdateDjangoDefinition(c echo.Context) error {
	objectType := api_v0.ObjectTypeDjangoDefinition
	fullyQualifiedType := new(api_v0.DjangoDefinition).GetFullyQualifiedType()
	djangoDefinitionID := c.Param("id")
	var existingDjangoDefinition api_v0.DjangoDefinition
	if result := h.Handler.RequestDB(c).First(&existingDjangoDefinition, djangoDefinitionID); result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return tpapiserver_lib.ResponseStatus404(c, nil, result.Error, fullyQualifiedType)
		}
		h.Handler.Logger.Error("handler error: error finding object", zap.Error(result.Error))
		return tpapiserver_lib.ResponseStatus500(c, nil, result.Error, fullyQualifiedType)
	}

	// check for empty payload, invalid or unsupported fields, optional associations, etc.
	if id, err := tpapiserver_lib.PayloadCheck(c, true, true, objectType, existingDjangoDefinition); err != nil {
		h.Handler.Logger.Error("handler error: error performing payload check", zap.Error(err))
		return tpapiserver_lib.ResponseStatusErr(id, c, nil, errors.New(err.Error()), fullyQualifiedType)
	}

	// bind payload
	var updatedDjangoDefinition api_v0.DjangoDefinition
	if err := c.Bind(&updatedDjangoDefinition); err != nil {
		h.Handler.Logger.Error("handler error: error binding payload", zap.Error(err))
		return tpapiserver_lib.ResponseStatusBindErr(c, nil, err, fullyQualifiedType)
	}

	// snapshot reconciliation state before update so the notify block
	// can skip publishing when the update did not touch any state marker
	prevReconciliation := existingDjangoDefinition.Reconciliation

	// update object in database
	if result := h.Handler.Write(c, func(db *gorm.DB) *gorm.DB {
		return db.Model(&existingDjangoDefinition).Updates(&updatedDjangoDefinition)
	}); result.Error != nil {
		h.Handler.Logger.Error("handler error: error updating object", zap.Error(result.Error))
		// check if this is a custom HTTP error with specific status code
		var httpErr *tputil_v0.HttpError
		if errors.As(result.Error, &httpErr) {
			return tpapiserver_lib.ResponseStatusErr(
				httpErr.GetStatusCode(), c, nil, result.Error, fullyQualifiedType,
			)
		}
		return tpapiserver_lib.RespondWriteError(
			c,
			h.Handler.Logger,
			result.Error,
			new(api_v0.DjangoDefinition),
			fullyQualifiedType,
		)
	}

	// notify controller if reconciliation is required and the update is notifiable
	if existingDjangoDefinition.Reconciled != nil && !*existingDjangoDefinition.Reconciled &&
		tpapi_v0.ReconciliationUpdateNotifiable(prevReconciliation, existingDjangoDefinition.Reconciliation) {
		notifPayload, err := existingDjangoDefinition.NotificationPayload(
			notifications.NotificationOperationUpdated,
			false,
			time.Now().Unix(),
		)
		if err != nil {
			h.Handler.Logger.Error("handler error: error creating NATS notification", zap.Error(err))
			return tpapiserver_lib.ResponseStatus500(c, nil, err, fullyQualifiedType)
		}
		h.Handler.JS.Publish(notif.DjangoDefinitionUpdateSubject, *notifPayload)
	}

	response, err := tpapiserver_lib.CreateResponse(
		tpapiserver_lib.SingleObjectMeta(),
		existingDjangoDefinition,
		fullyQualifiedType,
	)
	if err != nil {
		h.Handler.Logger.Error("handler error: error creating response", zap.Error(err))
		return tpapiserver_lib.ResponseStatus500(c, nil, err, fullyQualifiedType)
	}

	return tpapiserver_lib.ResponseStatus200(c, *response)
}

// @Summary updates an existing django definition by replacing the entire object.
// @Description Replace a django definition in the database.  All required fields must be provided.
// @Description If any optional fields are not provided, they will be null post-update.
// @Description Note: This API endpint is for updating django definition objects only.
// @Description Request bodies that include related objects will be accepted, however
// @Description the related objects will not be changed.  Call the patch or put method for
// @Description each particular existing object to change them.
// @ID replace-v0-djangoDefinition
// @Accept json
// @Produce json
// @Param id path int true "ID"
// @Param djangoDefinition body api_v0.DjangoDefinition true "DjangoDefinition object"
// @Success 200 {object} v0.Response "OK"
// @Failure 400 {object} v0.Response "Bad Request"
// @Failure 404 {object} v0.Response "Not Found"
// @Failure 409 {object} v0.Response "Conflict"
// @Failure 500 {object} v0.Response "Internal Server Error"
// @Router /threeport-io/v0/django-definitions/{id} [PUT]
func (h Handler) ReplaceDjangoDefinition(c echo.Context) error {
	objectType := api_v0.ObjectTypeDjangoDefinition
	fullyQualifiedType := new(api_v0.DjangoDefinition).GetFullyQualifiedType()
	djangoDefinitionID := c.Param("id")
	var existingDjangoDefinition api_v0.DjangoDefinition
	if result := h.Handler.RequestDB(c).First(&existingDjangoDefinition, djangoDefinitionID); result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return tpapiserver_lib.ResponseStatus404(c, nil, result.Error, fullyQualifiedType)
		}
		h.Handler.Logger.Error("handler error: error finding object", zap.Error(result.Error))
		return tpapiserver_lib.ResponseStatus500(c, nil, result.Error, fullyQualifiedType)
	}

	// check for empty payload, invalid or unsupported fields, optional associations, etc.
	if id, err := tpapiserver_lib.PayloadCheck(c, true, true, objectType, existingDjangoDefinition); err != nil {
		h.Handler.Logger.Error("handler error: error performing payload check", zap.Error(err))
		return tpapiserver_lib.ResponseStatusErr(id, c, nil, errors.New(err.Error()), fullyQualifiedType)
	}

	// bind payload
	var updatedDjangoDefinition api_v0.DjangoDefinition
	if err := c.Bind(&updatedDjangoDefinition); err != nil {
		h.Handler.Logger.Error("handler error: error binding payload", zap.Error(err))
		return tpapiserver_lib.ResponseStatusBindErr(c, nil, err, fullyQualifiedType)
	}

	// check for missing required fields
	if id, err := tpapiserver_lib.ValidateBoundData(c, updatedDjangoDefinition, objectType); err != nil {
		h.Handler.Logger.Error("handler error: error validating bound data", zap.Error(err))
		return tpapiserver_lib.ResponseStatusErr(id, c, nil, errors.New(err.Error()), fullyQualifiedType)
	}

	// snapshot reconciliation state before replace so the notify block
	// can skip publishing when the replace did not touch any state marker
	prevReconciliation := existingDjangoDefinition.Reconciliation

	// persist provided data
	updatedDjangoDefinition.ID = existingDjangoDefinition.ID
	if result := h.Handler.Write(c, func(db *gorm.DB) *gorm.DB {
		return db.Session(&gorm.Session{FullSaveAssociations: false}).Omit("CreatedAt", "DeletedAt").Save(&updatedDjangoDefinition)
	}); result.Error != nil {
		h.Handler.Logger.Error("handler error: error persisting object", zap.Error(result.Error))
		// check if this is a custom HTTP error with specific status code
		var httpErr *tputil_v0.HttpError
		if errors.As(result.Error, &httpErr) {
			return tpapiserver_lib.ResponseStatusErr(
				httpErr.GetStatusCode(), c, nil, result.Error, fullyQualifiedType,
			)
		}
		return tpapiserver_lib.RespondWriteError(
			c,
			h.Handler.Logger,
			result.Error,
			new(api_v0.DjangoDefinition),
			fullyQualifiedType,
		)
	}

	// reload updated data from DB
	if result := h.Handler.RequestDB(c).First(&existingDjangoDefinition, djangoDefinitionID); result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return tpapiserver_lib.ResponseStatus404(c, nil, result.Error, fullyQualifiedType)
		}
		h.Handler.Logger.Error("handler error: error finding object", zap.Error(result.Error))
		return tpapiserver_lib.ResponseStatus500(c, nil, result.Error, fullyQualifiedType)
	}

	// notify controller if reconciliation is required and the update is notifiable
	if existingDjangoDefinition.Reconciled != nil && !*existingDjangoDefinition.Reconciled &&
		tpapi_v0.ReconciliationUpdateNotifiable(prevReconciliation, existingDjangoDefinition.Reconciliation) {
		notifPayload, err := existingDjangoDefinition.NotificationPayload(
			notifications.NotificationOperationUpdated,
			false,
			time.Now().Unix(),
		)
		if err != nil {
			h.Handler.Logger.Error("handler error: error creating NATS notification", zap.Error(err))
			return tpapiserver_lib.ResponseStatus500(c, nil, err, fullyQualifiedType)
		}
		h.Handler.JS.Publish(notif.DjangoDefinitionUpdateSubject, *notifPayload)
	}

	response, err := tpapiserver_lib.CreateResponse(
		tpapiserver_lib.SingleObjectMeta(),
		existingDjangoDefinition,
		fullyQualifiedType,
	)
	if err != nil {
		h.Handler.Logger.Error("handler error: error creating response", zap.Error(err))
		return tpapiserver_lib.ResponseStatus500(c, nil, err, fullyQualifiedType)
	}

	return tpapiserver_lib.ResponseStatus200(c, *response)
}

// @Summary deletes a django definition.
// @Description Delete a django definition by ID from the database.
// @ID delete-v0-djangoDefinition
// @Accept json
// @Produce json
// @Param id path int true "ID"
// @Success 200 {object} v0.Response "OK"
// @Failure 404 {object} v0.Response "Not Found"
// @Failure 409 {object} v0.Response "Conflict"
// @Failure 500 {object} v0.Response "Internal Server Error"
// @Router /threeport-io/v0/django-definitions/{id} [DELETE]
func (h Handler) DeleteDjangoDefinition(c echo.Context) error {
	fullyQualifiedType := new(api_v0.DjangoDefinition).GetFullyQualifiedType()
	djangoDefinitionID := c.Param("id")
	var djangoDefinition api_v0.DjangoDefinition
	if result := h.Handler.RequestDB(c).Preload("DjangoInstances").First(&djangoDefinition, djangoDefinitionID); result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return tpapiserver_lib.ResponseStatus404(c, nil, result.Error, fullyQualifiedType)
		}
		h.Handler.Logger.Error("handler error: error finding object", zap.Error(result.Error))
		return tpapiserver_lib.ResponseStatus500(c, nil, result.Error, fullyQualifiedType)
	}

	// check to make sure no dependent instances exist for this definition
	if len(djangoDefinition.DjangoInstances) != 0 {
		err := errors.New("django definition has related django instances - " + tpapi_v0.ErrMsgDeleteBlocked)
		return tpapiserver_lib.ResponseStatus409(c, nil, err, fullyQualifiedType)
	}

	// pre-check synchronously so the client sees the 409 - without this, reconciled types only surface the block to the reconciler
	if checkErr := tpapi_v0.CheckBlockingAttachedObjectReferences(h.Handler.RequestDB(c), &djangoDefinition); checkErr != nil {
		var blockedErr *tpapi_v0.BlockedDeleteError
		if errors.As(checkErr, &blockedErr) {
			return tphandlers_v0.RespondBlockedDelete(
				c,
				h.Handler.RequestDB(c),
				blockedErr,
			)
		}
		return tpapiserver_lib.ResponseStatus500(c, nil, checkErr, fullyQualifiedType)
	}
	// schedule for deletion if not already scheduled
	// if scheduled and reconciled, delete object from DB
	// if scheduled but not reconciled, return 409 (controller is working on it)
	if djangoDefinition.DeletionScheduled == nil {
		// schedule for deletion
		reconciled := false
		timestamp := time.Now().UTC()
		scheduledDjangoDefinition := api_v0.DjangoDefinition{
			Reconciliation: tpapi_v0.Reconciliation{
				DeletionScheduled: &timestamp,
				Reconciled:        &reconciled,
			}}
		if result := h.Handler.Write(c, func(db *gorm.DB) *gorm.DB {
			return db.Model(&djangoDefinition).Updates(&scheduledDjangoDefinition)
		}); result.Error != nil {
			h.Handler.Logger.Error("handler error: error creating scheduled deletion", zap.Error(result.Error))
			return tpapiserver_lib.ResponseStatus500(c, nil, result.Error, fullyQualifiedType)
		}
		// notify controller
		notifPayload, err := djangoDefinition.NotificationPayload(
			notifications.NotificationOperationDeleted,
			false,
			time.Now().Unix(),
		)
		if err != nil {
			h.Handler.Logger.Error("handler error: error creating NATS notification", zap.Error(err))
			return tpapiserver_lib.ResponseStatus500(c, nil, err, fullyQualifiedType)
		}
		h.Handler.JS.Publish(notif.DjangoDefinitionDeleteSubject, *notifPayload)
	} else {
		if djangoDefinition.DeletionConfirmed == nil {
			// if deletion scheduled but not reconciled, return 409 - deletion
			// already underway
			return tpapiserver_lib.ResponseStatus409(c, nil, errors.New(fmt.Sprintf(
				"object with ID %d %s",
				*djangoDefinition.ID,
				tpapi_v0.ErrMsgAlreadyBeingDeleted,
			)), fullyQualifiedType)
		} else {
			// object scheduled for deletion and confirmed - it can be deleted
			// from DB
			if result := h.Handler.Write(c, func(db *gorm.DB) *gorm.DB {
				return db.Delete(&djangoDefinition)
			}); result.Error != nil {
				h.Handler.Logger.Error("handler error: error deleting object", zap.Error(result.Error))
				// surface BlockedDeleteError from gorm hook - backstop in case an attached object reference was created after the pre-check
				var blockedErr *tpapi_v0.BlockedDeleteError
				if errors.As(result.Error, &blockedErr) {
					return tphandlers_v0.RespondBlockedDelete(
						c,
						h.Handler.RequestDB(c),
						blockedErr,
					)
				}
				// check if this is a custom HTTP error with specific status code
				var httpErr *tputil_v0.HttpError
				if errors.As(result.Error, &httpErr) {
					return tpapiserver_lib.ResponseStatusErr(
						httpErr.GetStatusCode(), c, nil, result.Error, fullyQualifiedType,
					)
				}
				return tpapiserver_lib.ResponseStatus500(c, nil, result.Error, fullyQualifiedType)
			}
		}
	}

	// the delete has committed; drop any process state that mirrored the
	// row before answering. A persist hook cannot do this: a rollback
	// would have dropped state for a row that survived.
	if err := tpapiserver_lib.AfterCommitDelete(h.Handler.DB, &djangoDefinition); err != nil {
		h.Handler.Logger.Error("handler error: error reconciling process state after commit", zap.Error(err))
		return tpapiserver_lib.ResponseStatus500(c, nil, err, fullyQualifiedType)
	}

	response, err := tpapiserver_lib.CreateResponse(
		tpapiserver_lib.SingleObjectMeta(),
		djangoDefinition,
		fullyQualifiedType,
	)
	if err != nil {
		h.Handler.Logger.Error("handler error: error creating response", zap.Error(err))
		return tpapiserver_lib.ResponseStatus500(c, nil, err, fullyQualifiedType)
	}

	return tpapiserver_lib.ResponseStatus200(c, *response)
}

///////////////////////////////////////////////////////////////////////////////
// DjangoInstance
///////////////////////////////////////////////////////////////////////////////

// @Summary GetDjangoInstanceVersions gets the supported versions for the django instance API.
// @Description Get the supported API versions for django instances.
// @ID djangoInstance-get-versions
// @Produce json
// @Success 200 {object} tpapiserver_lib.ApiObjectVersions "OK"
// @Router /threeport-io/django-instances/versions [GET]
func (h Handler) GetDjangoInstanceVersions(c echo.Context) error {
	return c.JSON(http.StatusOK, tpapiserver_lib.ObjectVersions[string(api_v0.ObjectTypeDjangoInstance)])
}

// @Summary adds a new django instance.
// @Description Add a new django instance to the Threeport database.
// @ID add-v0-djangoInstance
// @Accept json
// @Produce json
// @Param djangoInstance body api_v0.DjangoInstance true "DjangoInstance object"
// @Success 201 {object} v0.Response "Created"
// @Failure 400 {object} v0.Response "Bad Request"
// @Failure 409 {object} v0.Response "Conflict"
// @Failure 500 {object} v0.Response "Internal Server Error"
// @Router /threeport-io/v0/django-instances [POST]
func (h Handler) AddDjangoInstance(c echo.Context) error {
	objectType := api_v0.ObjectTypeDjangoInstance
	fullyQualifiedType := new(api_v0.DjangoInstance).GetFullyQualifiedType()
	var djangoInstance api_v0.DjangoInstance

	// check for empty payload, unsupported fields, GORM Model fields, optional associations, etc.
	if id, err := tpapiserver_lib.PayloadCheck(c, true, false, objectType, djangoInstance); err != nil {
		h.Handler.Logger.Error("handler error: error performing payload check", zap.Error(err))
		return tpapiserver_lib.ResponseStatusErr(id, c, nil, errors.New(err.Error()), fullyQualifiedType)
	}

	if err := c.Bind(&djangoInstance); err != nil {
		h.Handler.Logger.Error("handler error: error binding object", zap.Error(err))
		return tpapiserver_lib.ResponseStatusBindErr(c, nil, err, fullyQualifiedType)
	}

	// check for missing required fields
	if id, err := tpapiserver_lib.ValidateBoundData(c, djangoInstance, objectType); err != nil {
		h.Handler.Logger.Error("handler error: error validating bound data", zap.Error(err))
		return tpapiserver_lib.ResponseStatusErr(id, c, nil, errors.New(err.Error()), fullyQualifiedType)
	}

	// persist to DB
	if result := h.Handler.Write(c, func(db *gorm.DB) *gorm.DB {
		// clear id so a retried create does not reuse a rolled-back key
		djangoInstance.ID = nil
		return db.Create(&djangoInstance)
	}); result.Error != nil {
		h.Handler.Logger.Error("handler error: error creating object", zap.Error(result.Error))
		// check if this is a custom HTTP error with specific status code
		var httpErr *tputil_v0.HttpError
		if errors.As(result.Error, &httpErr) {
			return tpapiserver_lib.ResponseStatusErr(
				httpErr.GetStatusCode(), c, nil, result.Error, fullyQualifiedType,
			)
		}
		return tpapiserver_lib.RespondWriteError(
			c,
			h.Handler.Logger,
			result.Error,
			new(api_v0.DjangoInstance),
			fullyQualifiedType,
		)
	}

	// the write has committed; bring any process state that mirrors the
	// database in line before answering, so a caller that gets a 200 can
	// rely on it. A persist hook cannot do this: it runs inside the
	// transaction, so it would act on a write that may never commit.
	if err := tpapiserver_lib.AfterCommitCreate(h.Handler.DB, &djangoInstance); err != nil {
		h.Handler.Logger.Error("handler error: error reconciling process state after commit", zap.Error(err))
		return tpapiserver_lib.ResponseStatus500(c, nil, err, fullyQualifiedType)
	}

	// notify controller if reconciliation is required
	if !*djangoInstance.Reconciled {
		notifPayload, err := djangoInstance.NotificationPayload(
			notifications.NotificationOperationCreated,
			false,
			time.Now().Unix(),
		)
		if err != nil {
			h.Handler.Logger.Error("handler error: error creating NATS notification", zap.Error(err))
			return tpapiserver_lib.ResponseStatus500(c, nil, err, fullyQualifiedType)
		}
		h.Handler.JS.Publish(notif.DjangoInstanceCreateSubject, *notifPayload)
	}

	response, err := tpapiserver_lib.CreateResponse(
		tpapiserver_lib.SingleObjectMeta(),
		djangoInstance,
		fullyQualifiedType,
	)
	if err != nil {
		h.Handler.Logger.Error("handler error: error creating response", zap.Error(err))
		return tpapiserver_lib.ResponseStatus500(c, nil, err, fullyQualifiedType)
	}

	return tpapiserver_lib.ResponseStatus201(c, *response)
}

// @Summary gets all django instances.
// @Description Get all django instances from the Threeport database.
// @ID get-v0-djangoInstances
// @Accept json
// @Produce json
// @Param name query string false "filter by exact django instance name (case sensitive)"
// @Success 200 {object} v0.Response "OK"
// @Failure 400 {object} v0.Response "Bad Request"
// @Failure 500 {object} v0.Response "Internal Server Error"
// @Router /threeport-io/v0/django-instances [GET]
func (h Handler) GetDjangoInstances(c echo.Context) error {
	fullyQualifiedType := new(api_v0.DjangoInstance).GetFullyQualifiedType()

	// get pagination parameters
	pageParams, err := c.(*tpapiserver_lib.CustomContext).GetPaginationParams()
	if err != nil {
		return tpapiserver_lib.ResponseStatus400(c, pageParams, err, fullyQualifiedType)
	}

	// bind filter
	var filter api_v0.DjangoInstance
	if err := c.Bind(&filter); err != nil {
		h.Handler.Logger.Error("handler error: error binding filter", zap.Error(err))
		return tpapiserver_lib.ResponseStatus400(c, pageParams, err, fullyQualifiedType)
	}

	pagination := new(tpapiserver_lib.Pagination)
	pagination.Limit = pageParams.Limit

	records := &[]api_v0.DjangoInstance{}
	var returnedCount int64

	switch {
	case pageParams.QueryId == "":
		// no query ID provided, so the client is not requesting a specific page of results
		// count total number of objects
		var totalCount int64
		if result := h.Handler.RequestDB(c).Model(&api_v0.DjangoInstance{}).Where(&filter).Count(&totalCount); result.Error != nil {
			h.Handler.Logger.Error("handler error: error counting objects", zap.Error(result.Error))
			return tpapiserver_lib.ResponseStatus500(c, pageParams, result.Error, fullyQualifiedType)
		}

		// see if total count is greater than the limit
		pagination.HasMore = totalCount > pagination.Limit

		switch pagination.HasMore {
		case false:
			// if we don't have to paginate, return all records
			if result := h.Handler.RequestDB(c).Order("ID asc").Where(&filter).Find(records); result.Error != nil {
				h.Handler.Logger.Error("handler error: error finding objects", zap.Error(result.Error))
				return tpapiserver_lib.ResponseStatus500(c, pageParams, result.Error, fullyQualifiedType)
			}
			returnedCount = int64(len(*records))
		case true:
			// dispatch to the configured pagination strategy to fetch the first page
			queryTable := filter.TableName()
			queryId, count, err := h.Handler.DispatchGetPaginatedRecords(h.Handler.RequestDB(c).Model(&api_v0.DjangoInstance{}).Where(&filter), records, queryTable, pageParams)
			if err != nil {
				if errors.Is(err, tpapiserver_lib.ErrInvalidPaginationQueryId) || errors.Is(err, tpapiserver_lib.ErrPaginationSessionExpired) {
					return tpapiserver_lib.ResponseStatus400(c, pageParams, err, fullyQualifiedType)
				}
				h.Handler.Logger.Error("handler error: error fetching paginated records", zap.Error(err))
				return tpapiserver_lib.ResponseStatus500(c, pageParams, err, fullyQualifiedType)
			}
			pagination.QueryId = queryId
			returnedCount = count

			// set the cursor for the next page of results
			if len(*records) > 0 {
				pagination.NextCursor = *(*records)[len(*records)-1].ID
			} else {
				pagination.NextCursor = 0
			}
		}
	case pageParams.QueryId != "" && pageParams.Cursor == 0:
		// client provided a query ID but no cursor, so we cannot fetch the next page of results
		return tpapiserver_lib.ResponseStatus400(c, pageParams, errors.New("cursor is required when query ID is provided"), fullyQualifiedType)
	case pageParams.QueryId != "" && pageParams.Cursor != 0:
		// continuation: dispatch to the configured pagination strategy to fetch the next page
		queryTable := filter.TableName()
		queryId, count, err := h.Handler.DispatchGetPaginatedRecords(h.Handler.RequestDB(c).Model(&api_v0.DjangoInstance{}).Where(&filter), records, queryTable, pageParams)
		if err != nil {
			if errors.Is(err, tpapiserver_lib.ErrInvalidPaginationQueryId) || errors.Is(err, tpapiserver_lib.ErrPaginationSessionExpired) {
				return tpapiserver_lib.ResponseStatus400(c, pageParams, err, fullyQualifiedType)
			}
			h.Handler.Logger.Error("handler error: error fetching paginated records", zap.Error(err))
			return tpapiserver_lib.ResponseStatus500(c, pageParams, err, fullyQualifiedType)
		}
		pagination.QueryId = queryId
		returnedCount = count

		// set the cursor for the next page of results
		if len(*records) > 0 {
			pagination.NextCursor = *(*records)[len(*records)-1].ID
		} else {
			pagination.NextCursor = 0
		}

		// see if we fetched the last of the records
		pagination.HasMore = returnedCount >= pagination.Limit
	}

	// construct response
	response, err := tpapiserver_lib.CreateResponse(
		&tpapiserver_lib.Meta{
			ObjectCount: returnedCount,
			Pagination:  *pagination,
		},
		*records,
		fullyQualifiedType,
	)
	if err != nil {
		h.Handler.Logger.Error("handler error: error creating response", zap.Error(err))
		return tpapiserver_lib.ResponseStatus500(c, pageParams, err, fullyQualifiedType)
	}

	return tpapiserver_lib.ResponseStatus200(c, *response)
}

// @Summary gets a django instance.
// @Description Get a particular django instance from the database.
// @ID get-v0-djangoInstance
// @Accept json
// @Produce json
// @Param id path int true "ID"
// @Success 200 {object} v0.Response "OK"
// @Failure 404 {object} v0.Response "Not Found"
// @Failure 500 {object} v0.Response "Internal Server Error"
// @Router /threeport-io/v0/django-instances/{id} [GET]
func (h Handler) GetDjangoInstance(c echo.Context) error {
	fullyQualifiedType := new(api_v0.DjangoInstance).GetFullyQualifiedType()
	djangoInstanceID := c.Param("id")
	var djangoInstance api_v0.DjangoInstance
	if result := h.Handler.RequestDB(c).
		First(&djangoInstance, djangoInstanceID); result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return tpapiserver_lib.ResponseStatus404(c, nil, result.Error, fullyQualifiedType)
		}
		h.Handler.Logger.Error("handler error: error finding object", zap.Error(result.Error))
		return tpapiserver_lib.ResponseStatus500(c, nil, result.Error, fullyQualifiedType)
	}

	response, err := tpapiserver_lib.CreateResponse(
		tpapiserver_lib.SingleObjectMeta(),
		djangoInstance,
		fullyQualifiedType,
	)
	if err != nil {
		h.Handler.Logger.Error("handler error: error creating response", zap.Error(err))
		return tpapiserver_lib.ResponseStatus500(c, nil, err, fullyQualifiedType)
	}

	return tpapiserver_lib.ResponseStatus200(c, *response)
}

// @Summary updates specific fields for an existing django instance.
// @Description Update a django instance in the database.  Provide one or more fields to update.
// @Description Note: This API endpint is for updating django instance objects only.
// @Description Request bodies that include related objects will be accepted, however
// @Description the related objects will not be changed.  Call the patch or put method for
// @Description each particular existing object to change them.
// @ID update-v0-djangoInstance
// @Accept json
// @Produce json
// @Param id path int true "ID"
// @Param djangoInstance body api_v0.DjangoInstance true "DjangoInstance object"
// @Success 200 {object} v0.Response "OK"
// @Failure 400 {object} v0.Response "Bad Request"
// @Failure 404 {object} v0.Response "Not Found"
// @Failure 409 {object} v0.Response "Conflict"
// @Failure 500 {object} v0.Response "Internal Server Error"
// @Router /threeport-io/v0/django-instances/{id} [PATCH]
func (h Handler) UpdateDjangoInstance(c echo.Context) error {
	objectType := api_v0.ObjectTypeDjangoInstance
	fullyQualifiedType := new(api_v0.DjangoInstance).GetFullyQualifiedType()
	djangoInstanceID := c.Param("id")
	var existingDjangoInstance api_v0.DjangoInstance
	if result := h.Handler.RequestDB(c).First(&existingDjangoInstance, djangoInstanceID); result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return tpapiserver_lib.ResponseStatus404(c, nil, result.Error, fullyQualifiedType)
		}
		h.Handler.Logger.Error("handler error: error finding object", zap.Error(result.Error))
		return tpapiserver_lib.ResponseStatus500(c, nil, result.Error, fullyQualifiedType)
	}

	// check for empty payload, invalid or unsupported fields, optional associations, etc.
	if id, err := tpapiserver_lib.PayloadCheck(c, true, true, objectType, existingDjangoInstance); err != nil {
		h.Handler.Logger.Error("handler error: error performing payload check", zap.Error(err))
		return tpapiserver_lib.ResponseStatusErr(id, c, nil, errors.New(err.Error()), fullyQualifiedType)
	}

	// bind payload
	var updatedDjangoInstance api_v0.DjangoInstance
	if err := c.Bind(&updatedDjangoInstance); err != nil {
		h.Handler.Logger.Error("handler error: error binding payload", zap.Error(err))
		return tpapiserver_lib.ResponseStatusBindErr(c, nil, err, fullyQualifiedType)
	}

	// snapshot reconciliation state before update so the notify block
	// can skip publishing when the update did not touch any state marker
	prevReconciliation := existingDjangoInstance.Reconciliation

	// update object in database
	if result := h.Handler.Write(c, func(db *gorm.DB) *gorm.DB {
		return db.Model(&existingDjangoInstance).Updates(&updatedDjangoInstance)
	}); result.Error != nil {
		h.Handler.Logger.Error("handler error: error updating object", zap.Error(result.Error))
		// check if this is a custom HTTP error with specific status code
		var httpErr *tputil_v0.HttpError
		if errors.As(result.Error, &httpErr) {
			return tpapiserver_lib.ResponseStatusErr(
				httpErr.GetStatusCode(), c, nil, result.Error, fullyQualifiedType,
			)
		}
		return tpapiserver_lib.RespondWriteError(
			c,
			h.Handler.Logger,
			result.Error,
			new(api_v0.DjangoInstance),
			fullyQualifiedType,
		)
	}

	// notify controller if reconciliation is required and the update is notifiable
	if existingDjangoInstance.Reconciled != nil && !*existingDjangoInstance.Reconciled &&
		tpapi_v0.ReconciliationUpdateNotifiable(prevReconciliation, existingDjangoInstance.Reconciliation) {
		notifPayload, err := existingDjangoInstance.NotificationPayload(
			notifications.NotificationOperationUpdated,
			false,
			time.Now().Unix(),
		)
		if err != nil {
			h.Handler.Logger.Error("handler error: error creating NATS notification", zap.Error(err))
			return tpapiserver_lib.ResponseStatus500(c, nil, err, fullyQualifiedType)
		}
		h.Handler.JS.Publish(notif.DjangoInstanceUpdateSubject, *notifPayload)
	}

	response, err := tpapiserver_lib.CreateResponse(
		tpapiserver_lib.SingleObjectMeta(),
		existingDjangoInstance,
		fullyQualifiedType,
	)
	if err != nil {
		h.Handler.Logger.Error("handler error: error creating response", zap.Error(err))
		return tpapiserver_lib.ResponseStatus500(c, nil, err, fullyQualifiedType)
	}

	return tpapiserver_lib.ResponseStatus200(c, *response)
}

// @Summary updates an existing django instance by replacing the entire object.
// @Description Replace a django instance in the database.  All required fields must be provided.
// @Description If any optional fields are not provided, they will be null post-update.
// @Description Note: This API endpint is for updating django instance objects only.
// @Description Request bodies that include related objects will be accepted, however
// @Description the related objects will not be changed.  Call the patch or put method for
// @Description each particular existing object to change them.
// @ID replace-v0-djangoInstance
// @Accept json
// @Produce json
// @Param id path int true "ID"
// @Param djangoInstance body api_v0.DjangoInstance true "DjangoInstance object"
// @Success 200 {object} v0.Response "OK"
// @Failure 400 {object} v0.Response "Bad Request"
// @Failure 404 {object} v0.Response "Not Found"
// @Failure 409 {object} v0.Response "Conflict"
// @Failure 500 {object} v0.Response "Internal Server Error"
// @Router /threeport-io/v0/django-instances/{id} [PUT]
func (h Handler) ReplaceDjangoInstance(c echo.Context) error {
	objectType := api_v0.ObjectTypeDjangoInstance
	fullyQualifiedType := new(api_v0.DjangoInstance).GetFullyQualifiedType()
	djangoInstanceID := c.Param("id")
	var existingDjangoInstance api_v0.DjangoInstance
	if result := h.Handler.RequestDB(c).First(&existingDjangoInstance, djangoInstanceID); result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return tpapiserver_lib.ResponseStatus404(c, nil, result.Error, fullyQualifiedType)
		}
		h.Handler.Logger.Error("handler error: error finding object", zap.Error(result.Error))
		return tpapiserver_lib.ResponseStatus500(c, nil, result.Error, fullyQualifiedType)
	}

	// check for empty payload, invalid or unsupported fields, optional associations, etc.
	if id, err := tpapiserver_lib.PayloadCheck(c, true, true, objectType, existingDjangoInstance); err != nil {
		h.Handler.Logger.Error("handler error: error performing payload check", zap.Error(err))
		return tpapiserver_lib.ResponseStatusErr(id, c, nil, errors.New(err.Error()), fullyQualifiedType)
	}

	// bind payload
	var updatedDjangoInstance api_v0.DjangoInstance
	if err := c.Bind(&updatedDjangoInstance); err != nil {
		h.Handler.Logger.Error("handler error: error binding payload", zap.Error(err))
		return tpapiserver_lib.ResponseStatusBindErr(c, nil, err, fullyQualifiedType)
	}

	// check for missing required fields
	if id, err := tpapiserver_lib.ValidateBoundData(c, updatedDjangoInstance, objectType); err != nil {
		h.Handler.Logger.Error("handler error: error validating bound data", zap.Error(err))
		return tpapiserver_lib.ResponseStatusErr(id, c, nil, errors.New(err.Error()), fullyQualifiedType)
	}

	// snapshot reconciliation state before replace so the notify block
	// can skip publishing when the replace did not touch any state marker
	prevReconciliation := existingDjangoInstance.Reconciliation

	// persist provided data
	updatedDjangoInstance.ID = existingDjangoInstance.ID
	if result := h.Handler.Write(c, func(db *gorm.DB) *gorm.DB {
		return db.Session(&gorm.Session{FullSaveAssociations: false}).Omit("CreatedAt", "DeletedAt").Save(&updatedDjangoInstance)
	}); result.Error != nil {
		h.Handler.Logger.Error("handler error: error persisting object", zap.Error(result.Error))
		// check if this is a custom HTTP error with specific status code
		var httpErr *tputil_v0.HttpError
		if errors.As(result.Error, &httpErr) {
			return tpapiserver_lib.ResponseStatusErr(
				httpErr.GetStatusCode(), c, nil, result.Error, fullyQualifiedType,
			)
		}
		return tpapiserver_lib.RespondWriteError(
			c,
			h.Handler.Logger,
			result.Error,
			new(api_v0.DjangoInstance),
			fullyQualifiedType,
		)
	}

	// reload updated data from DB
	if result := h.Handler.RequestDB(c).First(&existingDjangoInstance, djangoInstanceID); result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return tpapiserver_lib.ResponseStatus404(c, nil, result.Error, fullyQualifiedType)
		}
		h.Handler.Logger.Error("handler error: error finding object", zap.Error(result.Error))
		return tpapiserver_lib.ResponseStatus500(c, nil, result.Error, fullyQualifiedType)
	}

	// notify controller if reconciliation is required and the update is notifiable
	if existingDjangoInstance.Reconciled != nil && !*existingDjangoInstance.Reconciled &&
		tpapi_v0.ReconciliationUpdateNotifiable(prevReconciliation, existingDjangoInstance.Reconciliation) {
		notifPayload, err := existingDjangoInstance.NotificationPayload(
			notifications.NotificationOperationUpdated,
			false,
			time.Now().Unix(),
		)
		if err != nil {
			h.Handler.Logger.Error("handler error: error creating NATS notification", zap.Error(err))
			return tpapiserver_lib.ResponseStatus500(c, nil, err, fullyQualifiedType)
		}
		h.Handler.JS.Publish(notif.DjangoInstanceUpdateSubject, *notifPayload)
	}

	response, err := tpapiserver_lib.CreateResponse(
		tpapiserver_lib.SingleObjectMeta(),
		existingDjangoInstance,
		fullyQualifiedType,
	)
	if err != nil {
		h.Handler.Logger.Error("handler error: error creating response", zap.Error(err))
		return tpapiserver_lib.ResponseStatus500(c, nil, err, fullyQualifiedType)
	}

	return tpapiserver_lib.ResponseStatus200(c, *response)
}

// @Summary deletes a django instance.
// @Description Delete a django instance by ID from the database.
// @ID delete-v0-djangoInstance
// @Accept json
// @Produce json
// @Param id path int true "ID"
// @Success 200 {object} v0.Response "OK"
// @Failure 404 {object} v0.Response "Not Found"
// @Failure 409 {object} v0.Response "Conflict"
// @Failure 500 {object} v0.Response "Internal Server Error"
// @Router /threeport-io/v0/django-instances/{id} [DELETE]
func (h Handler) DeleteDjangoInstance(c echo.Context) error {
	fullyQualifiedType := new(api_v0.DjangoInstance).GetFullyQualifiedType()
	djangoInstanceID := c.Param("id")
	var djangoInstance api_v0.DjangoInstance
	if result := h.Handler.RequestDB(c).First(&djangoInstance, djangoInstanceID); result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return tpapiserver_lib.ResponseStatus404(c, nil, result.Error, fullyQualifiedType)
		}
		h.Handler.Logger.Error("handler error: error finding object", zap.Error(result.Error))
		return tpapiserver_lib.ResponseStatus500(c, nil, result.Error, fullyQualifiedType)
	}

	// pre-check synchronously so the client sees the 409 - without this, reconciled types only surface the block to the reconciler
	if checkErr := tpapi_v0.CheckBlockingAttachedObjectReferences(h.Handler.RequestDB(c), &djangoInstance); checkErr != nil {
		var blockedErr *tpapi_v0.BlockedDeleteError
		if errors.As(checkErr, &blockedErr) {
			return tphandlers_v0.RespondBlockedDelete(
				c,
				h.Handler.RequestDB(c),
				blockedErr,
			)
		}
		return tpapiserver_lib.ResponseStatus500(c, nil, checkErr, fullyQualifiedType)
	}
	// schedule for deletion if not already scheduled
	// if scheduled and reconciled, delete object from DB
	// if scheduled but not reconciled, return 409 (controller is working on it)
	if djangoInstance.DeletionScheduled == nil {
		// schedule for deletion
		reconciled := false
		timestamp := time.Now().UTC()
		scheduledDjangoInstance := api_v0.DjangoInstance{
			Reconciliation: tpapi_v0.Reconciliation{
				DeletionScheduled: &timestamp,
				Reconciled:        &reconciled,
			}}
		if result := h.Handler.Write(c, func(db *gorm.DB) *gorm.DB {
			return db.Model(&djangoInstance).Updates(&scheduledDjangoInstance)
		}); result.Error != nil {
			h.Handler.Logger.Error("handler error: error creating scheduled deletion", zap.Error(result.Error))
			return tpapiserver_lib.ResponseStatus500(c, nil, result.Error, fullyQualifiedType)
		}
		// notify controller
		notifPayload, err := djangoInstance.NotificationPayload(
			notifications.NotificationOperationDeleted,
			false,
			time.Now().Unix(),
		)
		if err != nil {
			h.Handler.Logger.Error("handler error: error creating NATS notification", zap.Error(err))
			return tpapiserver_lib.ResponseStatus500(c, nil, err, fullyQualifiedType)
		}
		h.Handler.JS.Publish(notif.DjangoInstanceDeleteSubject, *notifPayload)
	} else {
		if djangoInstance.DeletionConfirmed == nil {
			// if deletion scheduled but not reconciled, return 409 - deletion
			// already underway
			return tpapiserver_lib.ResponseStatus409(c, nil, errors.New(fmt.Sprintf(
				"object with ID %d %s",
				*djangoInstance.ID,
				tpapi_v0.ErrMsgAlreadyBeingDeleted,
			)), fullyQualifiedType)
		} else {
			// object scheduled for deletion and confirmed - it can be deleted
			// from DB
			if result := h.Handler.Write(c, func(db *gorm.DB) *gorm.DB {
				return db.Delete(&djangoInstance)
			}); result.Error != nil {
				h.Handler.Logger.Error("handler error: error deleting object", zap.Error(result.Error))
				// surface BlockedDeleteError from gorm hook - backstop in case an attached object reference was created after the pre-check
				var blockedErr *tpapi_v0.BlockedDeleteError
				if errors.As(result.Error, &blockedErr) {
					return tphandlers_v0.RespondBlockedDelete(
						c,
						h.Handler.RequestDB(c),
						blockedErr,
					)
				}
				// check if this is a custom HTTP error with specific status code
				var httpErr *tputil_v0.HttpError
				if errors.As(result.Error, &httpErr) {
					return tpapiserver_lib.ResponseStatusErr(
						httpErr.GetStatusCode(), c, nil, result.Error, fullyQualifiedType,
					)
				}
				return tpapiserver_lib.ResponseStatus500(c, nil, result.Error, fullyQualifiedType)
			}
		}
	}

	// the delete has committed; drop any process state that mirrored the
	// row before answering. A persist hook cannot do this: a rollback
	// would have dropped state for a row that survived.
	if err := tpapiserver_lib.AfterCommitDelete(h.Handler.DB, &djangoInstance); err != nil {
		h.Handler.Logger.Error("handler error: error reconciling process state after commit", zap.Error(err))
		return tpapiserver_lib.ResponseStatus500(c, nil, err, fullyQualifiedType)
	}

	response, err := tpapiserver_lib.CreateResponse(
		tpapiserver_lib.SingleObjectMeta(),
		djangoInstance,
		fullyQualifiedType,
	)
	if err != nil {
		h.Handler.Logger.Error("handler error: error creating response", zap.Error(err))
		return tpapiserver_lib.ResponseStatus500(c, nil, err, fullyQualifiedType)
	}

	return tpapiserver_lib.ResponseStatus200(c, *response)
}
