// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	"fmt"
	tpconfig_v0 "github.com/threeport/threeport/pkg/config/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
	"net/http"
)

// DjangoConfig is a container for a Django which is a config abstraction for
// the DjangoDefinition and DjangoInstance API objects.
// This abstraction allows users to manage definitions and instances together with single operations
// rather than separate operations for each API object.
type DjangoConfig struct {
	Django DjangoValues
}

// DjangoValues contains all the attributes needed to manage the
// DjangoDefinition and DjangoInstance API objects
// together with a single operation.
type DjangoValues struct {
	// Name is used for both the definition and the instance: a defined instance
	// is the pair that shares a name.
	Name *string

	// definition attributes
	Image          *string
	SettingsModule *string
	Environment    *string
	Replicas       *int
	RunMigrations  *bool

	// Additional environment variables. A defined instance is a one-to-one
	// pair, so there is nothing for an instance-level override to diverge
	// from: these are set on the definition. Use separate definition and
	// instance configs to override per instance.
	Env           *[]string
	SecretEnvVars []DjangoSecretEnvVarValues

	// instance attributes
	KubernetesRuntimeInstance *tpconfig_v0.KubernetesRuntimeInstanceValues
	SubDomain                 *string

	Age *string
}

// Get gets a django definition and instance from the Threeport API.
func (d *DjangoConfig) Get(
	apiClient *http.Client,
	apiEndpoint string,
	encryptionKey string,
) (*[]DjangoConfig, error) {
	// get operations
	operations, djangoDefinitions, djangoInstances := d.GetOperations(
		apiClient,
		apiEndpoint,
		encryptionKey,
	)

	// execute get operations
	if err := operations.Get(); err != nil {
		return nil, fmt.Errorf(
			"failed to execute get operations for django defined instances: %w",
			err,
		)
	}

	// assemble the defined instances
	djangoConfigs := mapToDjangoDefinedInstances(djangoDefinitions, djangoInstances)

	return djangoConfigs, nil
}

// Create creates a django definition and instance in the Threeport API.
func (d *DjangoConfig) Create(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]DjangoConfig, error) {
	// get operations
	operations, djangoDefinitions, djangoInstances := d.GetOperations(
		apiClient,
		apiEndpoint,
		"",
	)

	// execute create operations
	if err := operations.Create(); err != nil {
		return nil, fmt.Errorf(
			"failed to execute create operations for django defined instance %s: %w",
			djangoName(d.Django.Name),
			err,
		)
	}

	// assemble the defined instances
	djangoConfigs := mapToDjangoDefinedInstances(djangoDefinitions, djangoInstances)

	return djangoConfigs, nil
}

// Replace replaces a django definition and instance in the Threeport API.
func (d *DjangoConfig) Replace(
	apiClient *http.Client,
	apiEndpoint string,
	name string,
) (*[]DjangoConfig, error) {
	// get operations
	operations, djangoDefinitions, djangoInstances := d.GetOperations(
		apiClient,
		apiEndpoint,
		"",
	)

	// execute replace operations
	if err := operations.Replace(name); err != nil {
		return nil, fmt.Errorf(
			"failed to execute replace operations for django defined instance with name %s: %w",
			name,
			err,
		)
	}

	// assemble the defined instances
	djangoConfigs := mapToDjangoDefinedInstances(djangoDefinitions, djangoInstances)

	return djangoConfigs, nil
}

// Delete deletes a django definition and instance from the Threeport API.
func (d *DjangoConfig) Delete(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]DjangoConfig, error) {
	// get operations
	operations, _, _ := d.GetOperations(
		apiClient,
		apiEndpoint,
		"",
	)

	// execute delete operations
	if err := operations.Delete(); err != nil {
		return nil, fmt.Errorf(
			"failed to execute delete operations for django defined instance %s: %w",
			djangoName(d.Django.Name),
			err,
		)
	}

	return nil, nil
}

// djangoName describes a config's name for an error message. Validate reports a
// missing name, and these messages wrap the failure Validate returns, so the
// name has to be readable even when it is the thing that is absent.
func djangoName(name *string) string {
	if name == nil {
		return "with no name"
	}

	return fmt.Sprintf("with name %s", *name)
}

// GetOperations returns a slice of operations used to get, create, replace or delete
// a django defined instance.
func (d *DjangoConfig) GetOperations(
	apiClient *http.Client,
	apiEndpoint string,
	encryptionKey string,
) (*util.Operations, *[]DjangoDefinitionConfig, *[]DjangoInstanceConfig) {
	djangoValues := d.Django
	var err error
	var operatedDjangoDefinitions []DjangoDefinitionConfig
	var operatedDjangoInstances []DjangoInstanceConfig

	operations := util.Operations{}

	// add django definition operation
	djangoDefinitionConfig := DjangoDefinitionConfig{
		DjangoDefinition: DjangoDefinitionValues{
			Name:           djangoValues.Name,
			Image:          djangoValues.Image,
			SettingsModule: djangoValues.SettingsModule,
			Environment:    djangoValues.Environment,
			Replicas:       djangoValues.Replicas,
			RunMigrations:  djangoValues.RunMigrations,
			Env:            djangoValues.Env,
			SecretEnvVars:  djangoValues.SecretEnvVars,
			Age:            djangoValues.Age,
		},
	}
	operations.AppendOperation(util.Operation{
		Create: func() error {
			djangoDefinition, err := djangoDefinitionConfig.Create(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to create django definition %s: %w", djangoName(djangoValues.Name), err)
			}
			operatedDjangoDefinitions = append(operatedDjangoDefinitions, *djangoDefinition)
			return nil
		},
		Delete: func() error {
			_, err = djangoDefinitionConfig.Delete(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to delete django definition %s: %w", djangoName(djangoValues.Name), err)
			}
			return nil
		},
		Get: func() error {
			djangoDefinitions, err := djangoDefinitionConfig.Get(apiClient, apiEndpoint, encryptionKey)
			if err != nil {
				return fmt.Errorf("failed to get django definitions: %w", err)
			}
			operatedDjangoDefinitions = append(operatedDjangoDefinitions, *djangoDefinitions...)
			return nil
		},
		Name: "django definition",
		Replace: func(name string) error {
			djangoDefinition, err := djangoDefinitionConfig.Replace(apiClient, apiEndpoint, name)
			if err != nil {
				return fmt.Errorf("failed to replace django definition with name %s: %w", name, err)
			}
			operatedDjangoDefinitions = append(operatedDjangoDefinitions, *djangoDefinition)
			return nil
		},
	})

	// add django instance operation. The instance points at the definition the
	// operation above creates, which carries the same name.
	djangoInstanceConfig := DjangoInstanceConfig{
		DjangoInstance: DjangoInstanceValues{
			Name:                      djangoValues.Name,
			KubernetesRuntimeInstance: djangoValues.KubernetesRuntimeInstance,
			SubDomain:                 djangoValues.SubDomain,
			DjangoDefinition:          &DjangoDefinitionValues{Name: djangoValues.Name},
			Age:                       djangoValues.Age,
		},
	}
	operations.AppendOperation(util.Operation{
		Create: func() error {
			djangoInstance, err := djangoInstanceConfig.Create(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to create django instance %s: %w", djangoName(djangoValues.Name), err)
			}
			operatedDjangoInstances = append(operatedDjangoInstances, *djangoInstance)
			return nil
		},
		Delete: func() error {
			_, err = djangoInstanceConfig.Delete(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to delete django instance %s: %w", djangoName(djangoValues.Name), err)
			}
			return nil
		},
		Get: func() error {
			djangoInstances, err := djangoInstanceConfig.Get(apiClient, apiEndpoint, encryptionKey)
			if err != nil {
				return fmt.Errorf("failed to get django instances: %w", err)
			}
			operatedDjangoInstances = append(operatedDjangoInstances, *djangoInstances...)
			return nil
		},
		Name: "django instance",
		Replace: func(name string) error {
			djangoInstance, err := djangoInstanceConfig.Replace(apiClient, apiEndpoint, name)
			if err != nil {
				return fmt.Errorf("failed to replace django instance with name %s: %w", name, err)
			}
			operatedDjangoInstances = append(operatedDjangoInstances, *djangoInstance)
			return nil
		},
	})

	return &operations, &operatedDjangoDefinitions, &operatedDjangoInstances
}

// mapToDjangoDefinedInstances maps a slice of django definition and instance configs
// to a slice of django config objects
func mapToDjangoDefinedInstances(
	djangoDefinitions *[]DjangoDefinitionConfig,
	djangoInstances *[]DjangoInstanceConfig,
) *[]DjangoConfig {
	var djangoConfigs []DjangoConfig
	for _, inst := range *djangoInstances {
		// an instance with no name or no definition is not half of a defined
		// instance, and the comparisons below would dereference nil
		if inst.DjangoInstance.Name == nil ||
			inst.DjangoInstance.DjangoDefinition == nil ||
			inst.DjangoInstance.DjangoDefinition.Name == nil {
			continue
		}

		for _, def := range *djangoDefinitions {
			if def.DjangoDefinition.Name == nil {
				continue
			}
			instName := *inst.DjangoInstance.Name
			defName := *def.DjangoDefinition.Name
			// a defined instance must have matching names for definition and instance
			// and the definition must be associated with the instance
			if instName == defName && *inst.DjangoInstance.DjangoDefinition.Name == *def.DjangoDefinition.Name {
				djangoConfig := DjangoConfig{
					Django: DjangoValues{
						Name:                      inst.DjangoInstance.Name,
						Image:                     def.DjangoDefinition.Image,
						SettingsModule:            def.DjangoDefinition.SettingsModule,
						Environment:               def.DjangoDefinition.Environment,
						Replicas:                  def.DjangoDefinition.Replicas,
						RunMigrations:             def.DjangoDefinition.RunMigrations,
						Env:                       def.DjangoDefinition.Env,
						SecretEnvVars:             def.DjangoDefinition.SecretEnvVars,
						KubernetesRuntimeInstance: inst.DjangoInstance.KubernetesRuntimeInstance,
						SubDomain:                 inst.DjangoInstance.SubDomain,
						Age:                       inst.DjangoInstance.Age,
					},
				}
				djangoConfigs = append(djangoConfigs, djangoConfig)
				// an instance can only have one matching definition for a defined instance
				// we can break out of the loop after finding the first matching definition
				break
			}
		}
	}

	return &djangoConfigs
}
