// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	api_v0 "django-threeport-module/pkg/api/v0"
	client_v0 "django-threeport-module/pkg/client/v0"
	errors "errors"
	"fmt"
	tpapi_v0 "github.com/threeport/threeport/pkg/api/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
	"k8s.io/apimachinery/pkg/util/validation"
	"net/http"
	"strings"
)

// DjangoDefinitionConfig is a config abstraction for the DjangoDefinition API object.
// This abstraction allows users to manage API objects with a simplified set of attributes
// and remove the need for users to interract with API object details such as unique IDs
// and foreign keys.
type DjangoDefinitionConfig struct {
	DjangoDefinition DjangoDefinitionValues
}

// DjangoDefinitionValues contains all the attributes needed to manage
// the DjangoDefinition API object.
type DjangoDefinitionValues struct {
	Name *string

	// The container image for the Django application. Required: a Django
	// project has no canonical public image, so the module cannot deploy
	// anything without one.
	Image *string

	// The value for DJANGO_SETTINGS_MODULE, e.g. myapp.settings.production.
	SettingsModule *string

	// The environment the definition is deployed for. It becomes a Kubernetes
	// label and picks the replica and storage defaults; only "prod" is
	// special-cased, anything else gets the development sizing.
	Environment *string

	// The number of application pods. Left unset, the environment decides.
	Replicas *int

	// Whether django-admin migrate runs before the application is made
	// available. Left unset, the API defaults it to true.
	RunMigrations *bool

	// Additional literal environment variables as KEY=VALUE entries, applied to
	// every instance of the definition. Stored encrypted.
	Env *[]string

	// Additional environment variables sourced from existing Kubernetes
	// secrets, applied to every instance of the definition.
	SecretEnvVars []DjangoSecretEnvVarValues

	Age *string
}

// Get gets django definitions from the Threeport API.
// If the name is set in the DjangoDefinitionValues, it will return the django definition with that name.
// If the name is not set, it will return all django definitions.
func (d *DjangoDefinitionConfig) Get(
	apiClient *http.Client,
	apiEndpoint string,
	encryptionKey string,
) (*[]DjangoDefinitionConfig, error) {
	djangoDefinitionValues := d.DjangoDefinition

	// get API objects
	var djangoDefinitions *[]api_v0.DjangoDefinition
	switch {
	// if name is provided, get django definition by name
	case djangoDefinitionValues.Name != nil:
		djangoDefinition, err := client_v0.GetDjangoDefinitionByName(apiClient, apiEndpoint, *djangoDefinitionValues.Name)
		if err != nil {
			return nil, fmt.Errorf("failed to get django definition with name %s: %w", *djangoDefinitionValues.Name, err)
		}
		djangoDefinitions = &[]api_v0.DjangoDefinition{*djangoDefinition}
	// get all django definitions
	default:
		allDjangoDefinitions, err := client_v0.GetDjangoDefinitions(apiClient, apiEndpoint)
		if err != nil {
			return nil, fmt.Errorf("failed to get django definitions from Threeport API: %w", err)
		}
		djangoDefinitions = allDjangoDefinitions
	}

	// assemble config objects from API objects
	var djangoDefinitionConfigs []DjangoDefinitionConfig
	for _, djangoDefinition := range *djangoDefinitions {
		// literal env values are encrypted at rest: decrypt when the caller
		// supplied the key, redact otherwise
		djangoDefinition, err := decryptOrRedactDefinition(djangoDefinition, encryptionKey)
		if err != nil {
			return nil, err
		}

		djangoDefinitionConfig := DjangoDefinitionConfig{
			DjangoDefinition: DjangoDefinitionValues{
				Name:           djangoDefinition.Name,
				Image:          djangoDefinition.Image,
				SettingsModule: djangoDefinition.SettingsModule,
				Environment:    djangoDefinition.Environment,
				Replicas:       djangoDefinition.Replicas,
				RunMigrations:  djangoDefinition.RunMigrations,
				Env:            djangoDefinition.Env,
				SecretEnvVars:  secretEnvVarsFromAPI(djangoDefinition.SecretEnvVars),
				Age:            util.Ptr(util.GetAgeFormatted(djangoDefinition.CreatedAt)),
			},
		}
		djangoDefinitionConfigs = append(djangoDefinitionConfigs, djangoDefinitionConfig)
	}

	return &djangoDefinitionConfigs, nil
}

// Create creates a django definition in the Threeport API.
func (d *DjangoDefinitionConfig) Create(
	apiClient *http.Client,
	apiEndpoint string,
) (*DjangoDefinitionConfig, error) {
	djangoDefinitionValues := d.DjangoDefinition

	// validate config
	if err := d.Validate(); err != nil {
		// the name is not interpolated here: a missing name is one of the things
		// Validate reports, so reading it to describe the failure would panic on
		// exactly the config this line exists to explain
		return nil, fmt.Errorf("failed to validate values for django definition: %w", err)
	}

	// construct django definition object. Optional fields are passed through as
	// they arrive, including nil: the API applies its own defaults for
	// Environment and RunMigrations, and repeating them here would mean two
	// places to change when one of them moves.
	djangoDefinition := api_v0.DjangoDefinition{
		Definition: tpapi_v0.Definition{
			Name: djangoDefinitionValues.Name,
		},
		Image:          djangoDefinitionValues.Image,
		SettingsModule: djangoDefinitionValues.SettingsModule,
		Environment:    djangoDefinitionValues.Environment,
		Replicas:       djangoDefinitionValues.Replicas,
		RunMigrations:  djangoDefinitionValues.RunMigrations,
		Env:            djangoDefinitionValues.Env,
		SecretEnvVars:  secretEnvVarsToAPI(djangoDefinitionValues.SecretEnvVars),
	}

	// create django definition
	createdDjangoDefinition, err := client_v0.CreateDjangoDefinition(
		apiClient,
		apiEndpoint,
		&djangoDefinition,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to create django definition in threeport API: %w", err)
	}

	// construct django definition config
	createdDjangoDefinitionConfig := &DjangoDefinitionConfig{
		DjangoDefinition: DjangoDefinitionValues{
			Name:           createdDjangoDefinition.Name,
			Image:          createdDjangoDefinition.Image,
			SettingsModule: createdDjangoDefinition.SettingsModule,
			Environment:    createdDjangoDefinition.Environment,
			Replicas:       createdDjangoDefinition.Replicas,
			RunMigrations:  createdDjangoDefinition.RunMigrations,
			Env:            createdDjangoDefinition.Env,
			SecretEnvVars:  secretEnvVarsFromAPI(createdDjangoDefinition.SecretEnvVars),
			Age:            util.Ptr(util.GetAgeFormatted(createdDjangoDefinition.CreatedAt)),
		},
	}

	return createdDjangoDefinitionConfig, nil
}

// Replace updates the entire django definition object in the Threeport API.
// This is a full replacement of all fields in the django definition object.
// This function takes a name parameter to identify the django definition to replace.
// This allows a different name to be provided in the values object for name changes.
func (d *DjangoDefinitionConfig) Replace(
	apiClient *http.Client,
	apiEndpoint string,
	name string,
) (*DjangoDefinitionConfig, error) {
	djangoDefinitionValues := d.DjangoDefinition

	// validate config
	if err := d.Validate(); err != nil {
		return nil, fmt.Errorf("invalid django definition config: %w", err)
	}

	// get existing django definition by name
	existingDjangoDefinition, err := client_v0.GetDjangoDefinitionByName(
		apiClient,
		apiEndpoint,
		name,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find django definition with name %s: %w", name, err)
	}

	// the environment is rendered into the workload definition once, at
	// creation, so a replace cannot change it
	if err := checkEnvUnchanged(
		"django definition",
		djangoDefinitionValues.Env,
		djangoDefinitionValues.SecretEnvVars,
		existingDjangoDefinition.Env,
		existingDjangoDefinition.SecretEnvVars,
	); err != nil {
		return nil, err
	}

	// construct updated django definition object. This is a full replacement, so
	// every field the user can set is sent: a field left out of the config is
	// meant to be cleared, not carried over from the existing object.
	updatedDjangoDefinition := &api_v0.DjangoDefinition{
		Common: tpapi_v0.Common{
			ID: existingDjangoDefinition.ID,
		},
		Definition: tpapi_v0.Definition{
			Name: djangoDefinitionValues.Name,
		},
		Image:          djangoDefinitionValues.Image,
		SettingsModule: djangoDefinitionValues.SettingsModule,
		Environment:    djangoDefinitionValues.Environment,
		Replicas:       djangoDefinitionValues.Replicas,
		RunMigrations:  djangoDefinitionValues.RunMigrations,

		// carried over as stored: the values are ciphertext, which the API
		// recognises and does not encrypt again
		Env:           existingDjangoDefinition.Env,
		SecretEnvVars: existingDjangoDefinition.SecretEnvVars,

		// the workload definition is an owned relationship the reconciler sets,
		// not something the user configures. A replacement that left it out
		// would be asking the API to clear it, which it refuses because an owned
		// relationship is immutable once set.
		KubernetesWorkloadDefinitionID: existingDjangoDefinition.KubernetesWorkloadDefinitionID,
	}

	// replace django definition
	replacedDjangoDefinition, err := client_v0.ReplaceDjangoDefinition(
		apiClient,
		apiEndpoint,
		updatedDjangoDefinition,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to replace django definition in threeport API: %w", err)
	}

	// construct updated django definition config
	updatedDjangoDefinitionConfig := &DjangoDefinitionConfig{
		DjangoDefinition: DjangoDefinitionValues{
			Name:           replacedDjangoDefinition.Name,
			Image:          replacedDjangoDefinition.Image,
			SettingsModule: replacedDjangoDefinition.SettingsModule,
			Environment:    replacedDjangoDefinition.Environment,
			Replicas:       replacedDjangoDefinition.Replicas,
			RunMigrations:  replacedDjangoDefinition.RunMigrations,
			Env:            replacedDjangoDefinition.Env,
			SecretEnvVars:  secretEnvVarsFromAPI(replacedDjangoDefinition.SecretEnvVars),
			Age:            util.Ptr(util.GetAgeFormatted(replacedDjangoDefinition.CreatedAt)),
		},
	}

	return updatedDjangoDefinitionConfig, nil
}

// Delete deletes a django definition from the Threeport API.
func (d *DjangoDefinitionConfig) Delete(
	apiClient *http.Client,
	apiEndpoint string,
) (*DjangoDefinitionConfig, error) {
	djangoDefinitionValues := d.DjangoDefinition

	// delete works by name, and unlike create it does not run Validate first,
	// so the name is checked here rather than dereferenced blind
	if djangoDefinitionValues.Name == nil {
		return nil, errors.New("missing required field in config: Name")
	}

	// get django definition by name
	djangoDefinition, err := client_v0.GetDjangoDefinitionByName(
		apiClient,
		apiEndpoint,
		*djangoDefinitionValues.Name,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find django definition with name %s: %w", *djangoDefinitionValues.Name, err)
	}

	// delete django definition
	deletedDjangoDefinition, err := client_v0.DeleteDjangoDefinition(
		apiClient,
		apiEndpoint,
		*djangoDefinition.ID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to delete django definition from Threeport API: %w", err)
	}

	// construct deleted django definition config
	deletedDjangoDefinitionConfig := &DjangoDefinitionConfig{
		DjangoDefinition: DjangoDefinitionValues{
			Name: deletedDjangoDefinition.Name,
		},
	}

	return deletedDjangoDefinitionConfig, nil
}

// Validate validates inputs to create django definitions.
func (d *DjangoDefinitionConfig) Validate() error {
	djangoDefinitionValues := d.DjangoDefinition
	multiError := util.MultiError{}

	// ensure name is set
	if djangoDefinitionValues.Name == nil {
		multiError.AppendError(errors.New("missing required field in config: Name"))
	}

	// the name is the app.kubernetes.io/instance label on every object the
	// module renders, and also the prefix of the resource names, so it is
	// subject to the same late failure the environment check prevents
	if djangoDefinitionValues.Name != nil {
		if errs := validation.IsValidLabelValue(*djangoDefinitionValues.Name); len(errs) > 0 {
			multiError.AppendError(fmt.Errorf(
				"invalid value in config for Name: %s: %s",
				*djangoDefinitionValues.Name, strings.Join(errs, "; "),
			))
		}
	}

	// the API rejects a definition without an image, but it does so with a
	// database constraint error rather than something a user can act on
	if djangoDefinitionValues.Image == nil {
		multiError.AppendError(errors.New("missing required field in config: Image"))
	}

	// the environment becomes a Kubernetes label value. An invalid one is not
	// rejected until Threeport tries to apply the manifest, well after the
	// definition was accepted, so it is caught here instead.
	if djangoDefinitionValues.Environment != nil {
		if errs := validation.IsValidLabelValue(*djangoDefinitionValues.Environment); len(errs) > 0 {
			multiError.AppendError(fmt.Errorf(
				"invalid value in config for Environment: %s: %s",
				*djangoDefinitionValues.Environment, strings.Join(errs, "; "),
			))
		}
	}

	// a negative replica count is rejected by the kube API for the same reason,
	// and just as late
	if djangoDefinitionValues.Replicas != nil && *djangoDefinitionValues.Replicas < 0 {
		multiError.AppendError(fmt.Errorf(
			"invalid value in config for Replicas: %d: must not be negative",
			*djangoDefinitionValues.Replicas,
		))
	}

	if err := validateEnvVars(djangoDefinitionValues.Env, djangoDefinitionValues.SecretEnvVars); err != nil {
		multiError.AppendError(err)
	}

	return multiError.Error()
}
