// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	api_v0 "django-threeport-module/pkg/api/v0"
	client_v0 "django-threeport-module/pkg/client/v0"
	errors "errors"
	"fmt"
	tpapi_v0 "github.com/threeport/threeport/pkg/api/v0"
	tpclientlib "github.com/threeport/threeport/pkg/client/lib/v0"
	tpclient_v0 "github.com/threeport/threeport/pkg/client/v0"
	tpconfig_v0 "github.com/threeport/threeport/pkg/config/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
	"net/http"
)

// deletionWaitAttempts and deletionWaitSeconds bound the wait for a deleted
// instance to leave the API. They are variables rather than constants so a test
// can observe a timeout without sitting through a minute of it.
var (
	deletionWaitAttempts = 60
	deletionWaitSeconds  = 1
)

// DjangoInstanceConfig is a config abstraction for the DjangoInstance API object.
// This abstraction allows users to manage API objects with a simplified set of attributes
// and remove the need for users to interract with API object details such as unique IDs
// and foreign keys.
type DjangoInstanceConfig struct {
	DjangoInstance DjangoInstanceValues
}

// DjangoInstanceValues contains all the attributes needed to manage
// the DjangoInstance API object.
type DjangoInstanceValues struct {
	Name *string

	// The Kubernetes runtime to deploy to, named rather than referenced by ID.
	// Left unset, the control plane's default runtime is used, so a user with
	// one cluster does not have to name it.
	KubernetesRuntimeInstance *tpconfig_v0.KubernetesRuntimeInstanceValues

	// When a DomainName is in use, the subdomain to reach this instance on.
	SubDomain *string

	DjangoDefinition *DjangoDefinitionValues

	// Literal environment variables as KEY=VALUE entries for this instance
	// only. A name also set on the definition overrides it. Stored encrypted.
	// Applied when the instance is created.
	Env *[]string

	// Environment variables sourced from existing Kubernetes secrets for this
	// instance only. Overrides same-named variables on the definition.
	SecretEnvVars []DjangoSecretEnvVarValues

	Age *string
}

// Get gets django instances from the Threeport API.
// If the name is set in the DjangoInstanceValues, it will return the django instance with that name.
// If the name is not set, it will return all django instances.
func (d *DjangoInstanceConfig) Get(
	apiClient *http.Client,
	apiEndpoint string,
	encryptionKey string,
) (*[]DjangoInstanceConfig, error) {
	djangoInstanceValues := d.DjangoInstance

	// get API objects
	var djangoInstances *[]api_v0.DjangoInstance
	switch {
	// if name is provided, get django instance by name
	case djangoInstanceValues.Name != nil:
		djangoInstance, err := client_v0.GetDjangoInstanceByName(apiClient, apiEndpoint, *djangoInstanceValues.Name)
		if err != nil {
			return nil, fmt.Errorf("failed to get django instance with name %s: %w", *djangoInstanceValues.Name, err)
		}
		djangoInstances = &[]api_v0.DjangoInstance{*djangoInstance}
	// get all django instances
	default:
		allDjangoInstances, err := client_v0.GetDjangoInstances(apiClient, apiEndpoint)
		if err != nil {
			return nil, fmt.Errorf("failed to get django instances from Threeport API: %w", err)
		}
		djangoInstances = allDjangoInstances
	}

	// assemble config objects from API objects. Instances commonly share a
	// runtime and a definition, so resolved names are kept rather than fetched
	// again for every row.
	kubernetesRuntimeNames := make(map[uint]*string)
	djangoDefinitionNames := make(map[uint]*string)

	var djangoInstanceConfigs []DjangoInstanceConfig
	for _, djangoInstance := range *djangoInstances {
		// literal env values are encrypted at rest: decrypt when the caller
		// supplied the key, redact otherwise
		djangoInstance, err := decryptOrRedactInstance(djangoInstance, encryptionKey)
		if err != nil {
			return nil, err
		}

		// the runtime and definition are foreign keys on the API object; the
		// config abstraction exists so the user sees names instead
		var kubernetesRuntimeInstanceValues *tpconfig_v0.KubernetesRuntimeInstanceValues
		if djangoInstance.KubernetesRuntimeInstanceID != nil {
			id := *djangoInstance.KubernetesRuntimeInstanceID
			name, cached := kubernetesRuntimeNames[id]
			if !cached {
				kubernetesRuntimeInstance, err := tpclient_v0.GetKubernetesRuntimeInstanceByID(
					apiClient,
					apiEndpoint,
					id,
				)
				if err != nil {
					return nil, fmt.Errorf(
						"failed to get kubernetes runtime instance with ID %d: %w",
						id, err,
					)
				}
				name = kubernetesRuntimeInstance.Name
				kubernetesRuntimeNames[id] = name
			}
			kubernetesRuntimeInstanceValues = &tpconfig_v0.KubernetesRuntimeInstanceValues{Name: name}
		}

		var djangoDefinitionValues *DjangoDefinitionValues
		if djangoInstance.DjangoDefinitionID != nil {
			id := *djangoInstance.DjangoDefinitionID
			name, cached := djangoDefinitionNames[id]
			if !cached {
				djangoDefinition, err := client_v0.GetDjangoDefinitionByID(
					apiClient,
					apiEndpoint,
					id,
				)
				if err != nil {
					return nil, fmt.Errorf(
						"failed to get django definition with ID %d: %w",
						id, err,
					)
				}
				name = djangoDefinition.Name
				djangoDefinitionNames[id] = name
			}
			djangoDefinitionValues = &DjangoDefinitionValues{Name: name}
		}

		djangoInstanceConfig := DjangoInstanceConfig{
			DjangoInstance: DjangoInstanceValues{
				Name:                      djangoInstance.Name,
				KubernetesRuntimeInstance: kubernetesRuntimeInstanceValues,
				SubDomain:                 djangoInstance.SubDomain,
				DjangoDefinition:          djangoDefinitionValues,
				Env:                       djangoInstance.Env,
				SecretEnvVars:             secretEnvVarsFromAPI(djangoInstance.SecretEnvVars),
				Age:                       util.Ptr(util.GetAgeFormatted(djangoInstance.CreatedAt)),
			},
		}
		djangoInstanceConfigs = append(djangoInstanceConfigs, djangoInstanceConfig)
	}

	return &djangoInstanceConfigs, nil
}

// Create creates a django instance in the Threeport API.
func (d *DjangoInstanceConfig) Create(
	apiClient *http.Client,
	apiEndpoint string,
) (*DjangoInstanceConfig, error) {
	djangoInstanceValues := d.DjangoInstance

	// validate config
	if err := d.Validate(); err != nil {
		// see the note in DjangoDefinitionConfig.Create: a missing name is what
		// Validate reports, so it cannot be read to describe the failure
		return nil, fmt.Errorf("failed to validate values for django instance: %w", err)
	}

	// resolve the runtime and definition the config names into the foreign keys
	// the API object carries
	kubernetesRuntimeInstance, err := getKubernetesRuntimeInstanceByNameOrDefault(
		apiClient,
		apiEndpoint,
		djangoInstanceValues.KubernetesRuntimeInstance,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get kubernetes runtime instance: %w", err)
	}

	djangoDefinition, err := client_v0.GetDjangoDefinitionByName(
		apiClient,
		apiEndpoint,
		*djangoInstanceValues.DjangoDefinition.Name,
	)
	if err != nil {
		return nil, fmt.Errorf(
			"failed to find django definition with name %s: %w",
			*djangoInstanceValues.DjangoDefinition.Name, err,
		)
	}

	// construct django instance object
	djangoInstance := api_v0.DjangoInstance{
		Instance: tpapi_v0.Instance{
			Name: djangoInstanceValues.Name,
		},
		KubernetesRuntimeInstanceID: kubernetesRuntimeInstance.ID,
		SubDomain:                   djangoInstanceValues.SubDomain,
		DjangoDefinitionID:          djangoDefinition.ID,
		Env:                         djangoInstanceValues.Env,
		SecretEnvVars:               secretEnvVarsToAPI(djangoInstanceValues.SecretEnvVars),
	}

	// create django instance
	createdDjangoInstance, err := client_v0.CreateDjangoInstance(
		apiClient,
		apiEndpoint,
		&djangoInstance,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to create django instance in threeport API: %w", err)
	}

	// construct django instance config
	createdDjangoInstanceConfig := &DjangoInstanceConfig{
		DjangoInstance: DjangoInstanceValues{
			Name: createdDjangoInstance.Name,
			KubernetesRuntimeInstance: &tpconfig_v0.KubernetesRuntimeInstanceValues{
				Name: kubernetesRuntimeInstance.Name,
			},
			SubDomain:        createdDjangoInstance.SubDomain,
			Env:              createdDjangoInstance.Env,
			SecretEnvVars:    secretEnvVarsFromAPI(createdDjangoInstance.SecretEnvVars),
			DjangoDefinition: &DjangoDefinitionValues{Name: djangoDefinition.Name},
			Age:              util.Ptr(util.GetAgeFormatted(createdDjangoInstance.CreatedAt)),
		},
	}

	return createdDjangoInstanceConfig, nil
}

// Replace updates the entire django instance object in the Threeport API.
// This is a full replacement of all fields in the django instance object.
// This function takes a name parameter to identify the django instance to replace.
// This allows a different name to be provided in the values object for name changes.
func (d *DjangoInstanceConfig) Replace(
	apiClient *http.Client,
	apiEndpoint string,
	name string,
) (*DjangoInstanceConfig, error) {
	djangoInstanceValues := d.DjangoInstance

	// validate config
	if err := d.Validate(); err != nil {
		return nil, fmt.Errorf("invalid django instance config: %w", err)
	}

	// get existing django instance by name
	existingDjangoInstance, err := client_v0.GetDjangoInstanceByName(
		apiClient,
		apiEndpoint,
		name,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find django instance with name %s: %w", name, err)
	}

	// resolve the names the config carries into foreign keys. Unlike create,
	// this keeps the runtime the instance is already on rather than falling back
	// to the default, which would move the workload to another cluster on an
	// edit to an unrelated field.
	kubernetesRuntimeInstance, moved, err := getKubernetesRuntimeInstanceForReplace(
		apiClient,
		apiEndpoint,
		djangoInstanceValues.KubernetesRuntimeInstance,
		existingDjangoInstance.KubernetesRuntimeInstanceID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get kubernetes runtime instance: %w", err)
	}
	if moved {
		return nil, fmt.Errorf(
			"a django instance may not be moved from its current runtime to %s - create a new instance there instead",
			*djangoInstanceValues.KubernetesRuntimeInstance.Name,
		)
	}

	djangoDefinition, err := client_v0.GetDjangoDefinitionByName(
		apiClient,
		apiEndpoint,
		*djangoInstanceValues.DjangoDefinition.Name,
	)
	if err != nil {
		return nil, fmt.Errorf(
			"failed to find django definition with name %s: %w",
			*djangoInstanceValues.DjangoDefinition.Name, err,
		)
	}

	// the environment is rendered into the workload instance once, at
	// creation, so a replace cannot change it
	if err := checkEnvUnchanged(
		"django instance",
		djangoInstanceValues.Env,
		djangoInstanceValues.SecretEnvVars,
		existingDjangoInstance.Env,
		existingDjangoInstance.SecretEnvVars,
	); err != nil {
		return nil, err
	}

	// construct updated django instance object. This is a full replacement, so
	// every field the user can set is sent rather than merged onto the existing
	// object.
	updatedDjangoInstance := &api_v0.DjangoInstance{
		Common: tpapi_v0.Common{
			ID: existingDjangoInstance.ID,
		},
		Instance: tpapi_v0.Instance{
			Name: djangoInstanceValues.Name,
		},
		KubernetesRuntimeInstanceID: kubernetesRuntimeInstance.ID,
		SubDomain:                   djangoInstanceValues.SubDomain,
		DjangoDefinitionID:          djangoDefinition.ID,

		// carried over as stored: the values are ciphertext, which the API
		// recognises and does not encrypt again
		Env:           existingDjangoInstance.Env,
		SecretEnvVars: existingDjangoInstance.SecretEnvVars,

		// the workload instance is an owned relationship the reconciler sets,
		// not something the user configures. A replacement that left it out
		// would be asking the API to clear it, which it refuses because an owned
		// relationship is immutable once set.
		KubernetesWorkloadInstanceID: existingDjangoInstance.KubernetesWorkloadInstanceID,
	}

	// replace django instance
	replacedDjangoInstance, err := client_v0.ReplaceDjangoInstance(
		apiClient,
		apiEndpoint,
		updatedDjangoInstance,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to replace django instance in threeport API: %w", err)
	}

	// construct updated django instance config
	updatedDjangoInstanceConfig := &DjangoInstanceConfig{
		DjangoInstance: DjangoInstanceValues{
			Name: replacedDjangoInstance.Name,
			KubernetesRuntimeInstance: &tpconfig_v0.KubernetesRuntimeInstanceValues{
				Name: kubernetesRuntimeInstance.Name,
			},
			SubDomain:        replacedDjangoInstance.SubDomain,
			Env:              replacedDjangoInstance.Env,
			SecretEnvVars:    secretEnvVarsFromAPI(replacedDjangoInstance.SecretEnvVars),
			DjangoDefinition: &DjangoDefinitionValues{Name: djangoDefinition.Name},
			Age:              util.Ptr(util.GetAgeFormatted(replacedDjangoInstance.CreatedAt)),
		},
	}

	return updatedDjangoInstanceConfig, nil
}

// Delete deletes a django instance from the Threeport API.
func (d *DjangoInstanceConfig) Delete(
	apiClient *http.Client,
	apiEndpoint string,
) (*DjangoInstanceConfig, error) {
	djangoInstanceValues := d.DjangoInstance

	// delete works by name, and unlike create it does not run Validate first,
	// so the name is checked here rather than dereferenced blind
	if djangoInstanceValues.Name == nil {
		return nil, errors.New("missing required field in config: Name")
	}

	// get django instance by name
	djangoInstance, err := client_v0.GetDjangoInstanceByName(
		apiClient,
		apiEndpoint,
		*djangoInstanceValues.Name,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find django instance with name %s: %w", *djangoInstanceValues.Name, err)
	}

	// delete django instance
	deletedDjangoInstance, err := client_v0.DeleteDjangoInstance(
		apiClient,
		apiEndpoint,
		*djangoInstance.ID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to delete django instance from Threeport API: %w", err)
	}

	// wait for the django instance to be deleted. The API marks it for deletion
	// and the reconciler tears the workload down before the row goes away, so
	// returning immediately would let a caller deleting a defined instance try
	// to remove the definition while this instance still refers to it - which
	// the API refuses. Threeport's own instance configs wait the same way.
	if err := util.Retry(deletionWaitAttempts, deletionWaitSeconds, func() error {
		_, err := client_v0.GetDjangoInstanceByName(apiClient, apiEndpoint, *djangoInstanceValues.Name)
		if err == nil {
			return errors.New("django instance not deleted")
		}

		// only an explicit not found proves the row is gone. Any other error is
		// the API failing to answer, which says nothing about the instance, and
		// reading it as success would let a caller delete the definition while
		// this instance still refers to it.
		if errors.Is(err, tpclientlib.ErrObjectNotFound) {
			return nil
		}

		return fmt.Errorf("failed to check whether the django instance is deleted: %w", err)
	}); err != nil {
		return nil, fmt.Errorf(
			"gave up waiting for django instance %s to be deleted: %w",
			*djangoInstanceValues.Name, err,
		)
	}

	// construct deleted django instance config
	deletedDjangoInstanceConfig := &DjangoInstanceConfig{
		DjangoInstance: DjangoInstanceValues{
			Name: deletedDjangoInstance.Name,
		},
	}

	return deletedDjangoInstanceConfig, nil
}

// Validate validates inputs to create django instances.
func (d *DjangoInstanceConfig) Validate() error {
	djangoInstanceValues := d.DjangoInstance
	multiError := util.MultiError{}

	// ensure name is set
	if djangoInstanceValues.Name == nil {
		multiError.AppendError(errors.New("missing required field in config: Name"))
	}

	// an instance has nothing to deploy without a definition, and Create
	// dereferences the name to look it up
	if djangoInstanceValues.DjangoDefinition == nil || djangoInstanceValues.DjangoDefinition.Name == nil {
		multiError.AppendError(errors.New("missing required field in config: DjangoDefinition.Name"))
	}

	if err := validateEnvVars(djangoInstanceValues.Env, djangoInstanceValues.SecretEnvVars); err != nil {
		multiError.AppendError(err)
	}

	return multiError.Error()
}
